In [1]:
import pandas as pd
import numpy as np
import datetime

import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")
#!bash /Users/derekdewald/scripts/daily_shell_job.sh
# Learning Notes
# Process

In [43]:
from data_d_dicts import links

df = pd.read_csv(links['d_knowledge_base_url'])
df

,Process,Categorization,Word,Definition
0,ML Project,Process Step,Goal Setting,"Establish a clear, concise and explicit goal f..."
1,ML Project,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
2,ML Project,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
3,ML Project,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...
4,ML Project,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...
...,...,...,...,...
571,Generative AI,Definition,Self-consistency,Advanced technique in which the model generat...
572,Generative AI,Tooling,LangChain,Framework designed to simplify the development...
573,Langchain,Definition,Prompt templates,Key concept in LangChain. They help translate ...
574,Python,Guiding Principle,Python Function Naming Convention,Pythonic function naming follows the snake_cas...
575,Python,Guiding Principle,Data Set Column Naming,Dataset column naming should use ALL_CAPS_SNAK...

In [126]:
import os
os.getcwd()

'/Users/derekdewald/Documents/Python/Github_Repo/JupyterNotebooks'

In [128]:
def generate_process_output(df=pd.DataFrame(),process_list =['ML Project']):

    if len(df)==0:
        df = pd.read_csv(links['d_knowledge_base_url'])
    else:
        df = df.copy()

    final_df = pd.DataFrame()
    
    for process in process_list:
        final_df = pd.concat([
            final_df,
            generate_process_checklist(df,process)
        ])

    final_df.to_csv('/Users/derekdewald/Documents/Python/Github_Repo/Data/d_knowledge_process_checklist.csv',index=False)

generate_process_output()

,Process,Categorization,Word,Definition,baseorder1,baseorder2
16,Goal Setting,Process Step,Specific,Describes what will be accomplished and what s...,0,0
17,Goal Setting,Process Step,Measurable,Includes a clear way to track progress or dete...,0,1
18,Goal Setting,Process Step,Achievable,"Realistic given available time, resources, ski...",0,2
19,Goal Setting,Process Step,Relevant,"Aligns with broader priorities, such as team o...",0,3
20,Goal Setting,Process Step,Time Bound,Includes a clear deadline or timeframe for com...,0,4
21,Goal Setting,Process Step,Requirement,"Are Goals Documented. Are the Smart.\nIf not, ...",0,105
22,Problem Definition,Process Step,Desired State Metrics,Describe the target outcomes or performance le...,1,6
23,Problem Definition,Process Step,Current State Analysis,"Describes how the process, system, or situatio...",1,7
24,Problem Definition,Process Step,Root Cause Assessment,Identifies the underlying reasons why the prob...,1,8
25,Problem Definition,Process Step,Historical Overview,"Summarizes what actions, initiatives, or attem...",1,9

In [131]:
def generate_process_checklist(df=None,process_name='ML Project'):
    '''

    baseorder1: Count of De-duplicated Process - Word Order of Apperance.

    
    '''
    
    if len(df)==0:
        df = pd.read_csv(links['d_knowledge_base_url'])
    else:
        df = df.copy()

    # Base Order Mapping is to understand the Word Order for Process under consideration. As such needs to be a filtered DF, not the entire DF
    # Can Apply it to the entire DF, because all records which are contained in final Dataset MUST have it included for filtering, and will
    # Be dropped. 

    baseorder1_map = df[df['Process']==process_name].reset_index(drop=True).reset_index().set_index('Word')['index'].to_dict()
    df['baseorder1'] = df['Word'].map(baseorder1_map)
    
    # Start with Process. Merge In Components of Word
    base_df = df[df['Process']==process_name].copy()
    
    process_extension = df[df['Process'].isin(base_df['Word'])].drop('baseorder1',axis=1).copy()
    baseorder2_map = process_extension.reset_index(drop=True).reset_index().set_index('Word')['index'].to_dict()
    process_extension['baseorder1'] = process_extension['Process'].map(baseorder1_map)
    process_extension['baseorder2'] = process_extension['Word'].map(baseorder2_map)
    display(process_extension.head(10))
    process_extension['Categorization'] = process_extension['Process'].copy()
    process_extension['Process'] = process_name

    base_df = pd.concat([
        base_df,
        process_extension
    ]).fillna(0).sort_values(['baseorder1','baseorder2'])  
    
    return base_df.drop(['baseorder1','baseorder2'],axis=1)
    
df1 = generate_process_checklist(df)
df1.head(10)

,Process,Categorization,Word,Definition,baseorder1,baseorder2
16,Goal Setting,Process Step,Specific,Describes what will be accomplished and what s...,0,0
17,Goal Setting,Process Step,Measurable,Includes a clear way to track progress or dete...,0,1
18,Goal Setting,Process Step,Achievable,"Realistic given available time, resources, ski...",0,2
19,Goal Setting,Process Step,Relevant,"Aligns with broader priorities, such as team o...",0,3
20,Goal Setting,Process Step,Time Bound,Includes a clear deadline or timeframe for com...,0,4
21,Goal Setting,Process Step,Requirement,"Are Goals Documented. Are the Smart.\nIf not, ...",0,105
22,Problem Definition,Process Step,Desired State Metrics,Describe the target outcomes or performance le...,1,6
23,Problem Definition,Process Step,Current State Analysis,"Describes how the process, system, or situatio...",1,7
24,Problem Definition,Process Step,Root Cause Assessment,Identifies the underlying reasons why the prob...,1,8
25,Problem Definition,Process Step,Historical Overview,"Summarizes what actions, initiatives, or attem...",1,9

,Process,Categorization,Word,Definition
0,ML Project,Process Step,Goal Setting,"Establish a clear, concise and explicit goal f..."
16,ML Project,Goal Setting,Specific,Describes what will be accomplished and what s...
17,ML Project,Goal Setting,Measurable,Includes a clear way to track progress or dete...
18,ML Project,Goal Setting,Achievable,"Realistic given available time, resources, ski..."
19,ML Project,Goal Setting,Relevant,"Aligns with broader priorities, such as team o..."
20,ML Project,Goal Setting,Time Bound,Includes a clear deadline or timeframe for com...
21,ML Project,Goal Setting,Requirement,"Are Goals Documented. Are the Smart.\nIf not, ..."
1,ML Project,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
22,ML Project,Problem Definition,Desired State Metrics,Describe the target outcomes or performance le...
23,ML Project,Problem Definition,Current State Analysis,"Describes how the process, system, or situatio..."

In [122]:
df1.to_excel('test.xlsx',index=False)

In [99]:
df1[df1['Categorization']=='Problem Definition')]

Empty DataFrame
Columns: [Process, Categorization, Word, Definition, baseorder1]
Index: []

In [100]:
df[df['Process'] == 'Problem Definition']

,Process,Categorization,Word,Definition
22,Problem Definition,Process Step,Desired State Metrics,Describe the target outcomes or performance le...
23,Problem Definition,Process Step,Current State Analysis,"Describes how the process, system, or situatio..."
24,Problem Definition,Process Step,Root Cause Assessment,Identifies the underlying reasons why the prob...
25,Problem Definition,Process Step,Historical Overview,"Summarizes what actions, initiatives, or attem..."
26,Problem Definition,Process Step,Baseline Metrics (Current State),Quantify the current state of the problem usin...
27,Problem Definition,Process Step,Requirement,Attempt to explicitly define outcomes and rele...
28,Problem Definition,Process Step,Requirement,Must be careful at how problem is defined. Is ...
29,Problem Definition,Process Step,Consideration,How Invested are stakeholders in defining the ...
30,Problem Definition,Process Step,Consideration,Proceed with extreme caution where the problem...

In [31]:
order_map

{'Goal Setting': 0,
 'Problem Definition': 1,
 'Data Collection': 2,
 'Data Preparation': 3,
 'Exploratory Data Analysis': 4,
 'Feature Engineering': 5,
 'Feature Selection': 6,
 'Validation/ Model Selection': 7,
 'Training': 8,
 'Hyperparameter Tuning': 9,
 'Model Evaluation': 10,
 'Validation': 11,
 'Model Summarization / Model Interpretability': 12,
 'Deployment': 13,
 'Monitoring': 14,
 'Bias, Fairness, and Ethics': 15}

In [81]:
from df_processing import df_to_dict

# For all Words, Which are effecetively Steps, Merge in the Individual components of the steps from Notes.
base_word = base_df['Word'].unique()
expanded_df = df[df['Process'].isin(base_word)].copy()
expanded_df['DF_RANK']=2
expanded_df['ORDER'] = expanded_df['Process'].map(order_map)
expanded_df['ORDER_'] = [x for x in range(2,len(expanded_df)+2)]
expanded_df['Categorization'] = expanded_df['Process'].copy()

# Process Value is moved to Categorization  
# Process Value becomes Main Process Value.
expanded_df['Process'] = process_name
# Need to allign Columns for Concatting

final_df = pd.concat([base_df,expanded_df]).sort_values(['ORDER','DF_RANK','ORDER_'])
final_df.drop(['ORDER','DF_RANK','ORDER_'],axis=1,inplace=True)

In [78]:
base_df.head()

,Process,Categorization,Word,Definition,DF_RANK,ORDER,ORDER_
0,ML Project,Process Step,Goal Setting,"Establish a clear, concise and explicit goal f...",1,1,1
1,ML Project,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th...",1,2,1
2,ML Project,Process Step,Data Collection,"Data collection involves identifying, sourcing...",1,3,1
3,ML Project,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...,1,4,1
4,ML Project,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...,1,5,1

In [82]:
expanded_df.head()

,Process,Categorization,Word,Definition,DF_RANK,ORDER,ORDER_
16,ML Project,Goal Setting,Specific,Describes what will be accomplished and what s...,2,1,2
17,ML Project,Goal Setting,Measurable,Includes a clear way to track progress or dete...,2,1,3
18,ML Project,Goal Setting,Achievable,"Realistic given available time, resources, ski...",2,1,4
19,ML Project,Goal Setting,Relevant,"Aligns with broader priorities, such as team o...",2,1,5
20,ML Project,Goal Setting,Time Bound,Includes a clear deadline or timeframe for com...,2,1,6

In [97]:
final_df = pd.concat([base_df,expanded_df]).sort_values(['ORDER','DF_RANK','ORDER_'])

final_df.to_excel('test.xlsx',index=False)
final_df.head(30)

,Process,Categorization,Word,Definition,DF_RANK,ORDER,ORDER_
0,ML Project,Process Step,Goal Setting,"Establish a clear, concise and explicit goal f...",1,1,1
16,ML Project,Goal Setting,Specific,Describes what will be accomplished and what s...,2,1,2
17,ML Project,Goal Setting,Measurable,Includes a clear way to track progress or dete...,2,1,3
18,ML Project,Goal Setting,Achievable,"Realistic given available time, resources, ski...",2,1,4
19,ML Project,Goal Setting,Relevant,"Aligns with broader priorities, such as team o...",2,1,5
20,ML Project,Goal Setting,Time Bound,Includes a clear deadline or timeframe for com...,2,1,6
21,ML Project,Goal Setting,Requirement,"Are Goals Documented. Are the Smart.\nIf not, ...",2,1,7
1,ML Project,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th...",1,2,1
22,ML Project,Problem Definition,Desired State Metrics,Describe the target outcomes or performance le...,2,2,8
23,ML Project,Problem Definition,Current State Analysis,"Describes how the process, system, or situatio...",2,2,9
24,ML Project,Problem Definition,Root Cause Assessment,Identifies the underlying reasons why the prob...,2,2,10
25,ML Project,Problem Definition,Historical Overview,"Summarizes what actions, initiatives, or attem...",2,2,11
26,ML Project,Problem Definition,Baseline Metrics (Current State),Quantify the current state of the problem usin...,2,2,12
27,ML Project,Problem Definition,Requirement,Attempt to explicitly define outcomes and rele...,2,2,13
28,ML Project,Problem Definition,Requirement,Must be careful at how problem is defined. Is ...,2,2,14
29,ML Project,Problem Definition,Consideration,How Invested are stakeholders in defining the ...,2,2,15
30,ML Project,Problem Definition,Consideration,Proceed with extreme caution where the problem...,2,2,16
2,ML Project,Process Step,Data Collection,"Data collection involves identifying, sourcing...",1,3,1
31,ML Project,Data Collection,Requirement,What consessions have we made due to a lack of...,2,3,17
32,ML Project,Data Collection,Requirement,"Who is the Data Steward, are they involved, an...",2,3,18
33,ML Project,Data Collection,Requirement,"Review Semantic and Functional Definitions, en...",2,3,19
3,ML Project,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...,1,4,1
34,ML Project,Data Preparation,Baseline,Baseline represents the typical or expected be...,2,4,20
35,ML Project,Data Preparation,Dimension,A Dimension is a conceptual axis of behavior o...,2,4,21
36,ML Project,Data Preparation,Implementation,An Implementation is a specific measurable rep...,2,4,22
37,ML Project,Data Preparation,Momentum,Momentum represents the direction and rate of ...,2,4,23
38,ML Project,Data Preparation,Parameter,A Parameter is a tuning choice that controls h...,2,4,24
39,ML Project,Data Preparation,Volatility,Volatility represents the consistency or varia...,2,4,25
40,ML Project,Data Preparation,Semantic Type,Influenced by the literal definition of semant...,2,4,26
41,ML Project,Data Preparation,Functional Role,Describes how a variable is used within a spec...,2,4,27

In [92]:
final_df[(final_df['Word']=='Goal Setting')|(final_df['Categorization']=='Goal Setting')]

,Process,Categorization,Word,Definition,DF_RANK,ORDER,ORDER_
0,ML Project,Process Step,Goal Setting,"Establish a clear, concise and explicit goal f...",1,1,1
16,ML Project,Goal Setting,Specific,Describes what will be accomplished and what s...,2,1,2
17,ML Project,Goal Setting,Measurable,Includes a clear way to track progress or dete...,2,1,3
18,ML Project,Goal Setting,Achievable,"Realistic given available time, resources, ski...",2,1,4
19,ML Project,Goal Setting,Relevant,"Aligns with broader priorities, such as team o...",2,1,5
20,ML Project,Goal Setting,Time Bound,Includes a clear deadline or timeframe for com...,2,1,6
21,ML Project,Goal Setting,Requirement,"Are Goals Documented. Are the Smart.\nIf not, ...",2,1,7

In [40]:
# Create Process Check List

def create_process_check_list(df,process_name):
    '''
    
    
    '''

,Process,Categorization,Word,Definition
0,ML Project,Process Step,Goal Setting,"Establish a clear, concise and explicit goal f..."
1,ML Project,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
2,ML Project,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
3,ML Project,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...
4,ML Project,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...
...,...,...,...,...
571,Generative AI,Definition,Self-consistency,Advanced technique in which the model generat...
572,Generative AI,Tooling,LangChain,Framework designed to simplify the development...
573,Langchain,Definition,Prompt templates,Key concept in LangChain. They help translate ...
574,Python,Guiding Principle,Python Function Naming Convention,Pythonic function naming follows the snake_cas...
575,Python,Guiding Principle,Data Set Column Naming,Dataset column naming should use ALL_CAPS_SNAK...

In [2]:
from data_d_dicts import links

df = pd.read_csv(links['d_knowledge_base_url'])
df

,Process,Categorization,Word,Definition
0,ML Project,Process Step,Goal Setting,"Establish a clear, concise and explicit goal f..."
1,ML Project,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
2,ML Project,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
3,ML Project,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...
4,ML Project,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...
...,...,...,...,...
571,Generative AI,Definition,Self-consistency,Advanced technique in which the model generat...
572,Generative AI,Tooling,LangChain,Framework designed to simplify the development...
573,Langchain,Definition,Prompt templates,Key concept in LangChain. They help translate ...
574,Python,Guiding Principle,Python Function Naming Convention,Pythonic function naming follows the snake_cas...
575,Python,Guiding Principle,Data Set Column Naming,Dataset column naming should use ALL_CAPS_SNAK...

In [28]:
from data_d_strings import template_doc_string_print

template_doc_string_print()

    Definition of Function

    Parameters:
        List of Parameters

    Returns:
        Object Type

    date_created:16-Feb-26
    date_last_modified: 16-Feb-26
    classification:TBD
    sub_classification:TBD
    usage:
        Example Function Call

In [ ]:
# Make it clear, the Check List, ONLY LOOKS AT MILESTONES. Define Milestonse in Read Me.

In [37]:
def create_blank_insert_knowledge_base(df,
                                       process,
                                       sub_process=None):
    
    '''
    A Function which supports the update and maintenace of the D Knowledge Base.
    Function provides 2 Unique Purposes.

    1) Create a Generic Base based on a Defined Process (Specifically at development, ML Project), which supports providing a Framework
    for inclusion, by identifying the relevant steps which should be included as a base.

    

    2) Modfies the existing Knowledge base and creates Modified Check Process Checklist, which HAS to be used for respective Project. 

    Parameters:
        List of Parameters

    Returns:
        Object Type

    date_created:16-Feb-26
    date_last_modified: 16-Feb-26
    classification:TBD
    sub_classification:TBD
    usage:
        
        df = pd.read_csv(links['d_knowledge_base_url'])
        create_blank_insert_knowledge_base(df,'ML Project')
        create_blank_insert_knowledge_base(df,'ML Project','Clustering')


    '''
    # Step 1 Create A Framework Based on steps in defined process.
    base_df = df[df['Process']==process].drop('Definition',axis=1).copy()
    #base_df['Process'] = process_name

    if not sub_process:
        return base_df

    else:
        # Step 2 Merge in All of the Values from the Process which Are Process Steps and Align with ML Project

        base_df = df[df['Process']==process].copy()
        sub_step = df[(df['Process']==process_name)&(df['Categorization']=='Process Step')]


        return base_df,sub_step
        
        final_df = base_df.merge(sub_step.drop('Process',axis=1),on=['Categorization','Word'],how='left',suffixes=("","_"))
        
        return final_df
        
        final_df = final_df.merge(not_pr_step.drop(['Process'],axis=1),left_on= 'Word',right_on='Categorization',how='left',suffixes=("","_")).drop('Categorization_',axis=1)
        final_df['Categorization'] = np.where(final_df['Word_'].notnull(),final_df['Word'],d['Categorization'])
        final_df['Word'] = np.where(final_df['Word_'].notnull(),final_df['Word_'],final_df['Word'])
        final_df['Definition'] = np.where(final_df['Word_'].notnull(),final_df['Definition_'].fillna(""),final_df['Definition'].fillna(""))
        final_df.drop(['Word_','Definition_'],axis=1,inplace=True)
        final_df['Process'] = sub_process

        return final_df


a,b= create_blank_insert_knowledge_base(df,'ML Project','Clustering')

In [38]:
a

,Process,Categorization,Word,Definition
0,ML Project,Process Step,Goal Setting,"Establish a clear, concise and explicit goal f..."
1,ML Project,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
2,ML Project,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
3,ML Project,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...
4,ML Project,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...
5,ML Project,Process Step,Feature Engineering,Process of creating new input variables that b...
6,ML Project,Process Step,Feature Selection,Process of identifying and retaining the most ...
7,ML Project,Process Step,Validation/ Model Selection,The process of choosing the most appropriate a...
8,ML Project,Process Step,Training,Process of fitting a machine learning model to...
9,ML Project,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...
10,ML Project,Process Step,Model Evaluation,Process of measuring how well a trained model ...
11,ML Project,Process Step,Validation,Validation is the process of assessing model p...
12,ML Project,Process Step,Model Summarization / Model Interpretability,Process of explaining how a model makes predic...
13,ML Project,Process Step,Deployment,Deployment is the process of integrating the t...
14,ML Project,Process Step,Monitoring,Ongoing process of tracking model performance ...
15,ML Project,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...

In [39]:
b

,Process,Categorization,Word,Definition
139,Clustering,Process Step,Goal Setting,Goals of a clustering project can greatly diff...
140,Clustering,Process Step,Goal Setting,"A classification, via calculation utilizing ma..."
141,Clustering,Process Step,Problem Definition,"When choosing, need to have a explicit underst..."
142,Clustering,Process Step,Problem Definition,"Define the intended use, boundaries, and decis..."
143,Clustering,Process Step,Data Collection,Identify and validate the behavioural attribut...
144,Clustering,Process Step,Data Preparation,Ensure Data is Labelled and Categorized.
145,Clustering,Process Step,Data Preparation,"Review Semantic Classifications, insure suffic..."
146,Clustering,Process Step,Feature Selection,Correlation & Redundancy Analysis. If Greater ...
147,Clustering,Process Step,Feature Selection,Variance & Stability Contribution: Variance In...
148,Clustering,Process Step,Feature Selection,Clustering Sensitivity / Stability Tests\n1. T...
149,Clustering,Process Step,Feature Selection,4. Incremental Value via Feature Importance in...
150,Clustering,Process Step,Feature Selection,Understand the relative contribution and sensi...
151,Clustering,Process Step,Validation/ Model Selection,"Identify and define distinct, stable member ar..."
152,Clustering,Process Step,Model Summarization / Model Interpretability,"Characterize each archetype using clear, inter..."
153,Clustering,Process Step,Model Summarization / Model Interpretability,Design and apply differentiated engagement str...
154,Clustering,Process Step,Monitoring,"Monitor archetype-level outcomes, migration, a..."

In [24]:
process_name='Clustering'
process_type='ML Project'

# We Want to Enable A Process to have a Specific Structure in the Notes Sheet. This aligns its structure to the ML Project.







pr_step = df[(df['Process']==process_name)&(df['Categorization']=='Process Step')]
not_pr_step = df[(df['Process']==process_name)&(df['Categorization']!='Process Step')]

d = base_df.merge(pr_step.drop('Process',axis=1),on=['Categorization','Word'],how='left')


d = d.merge(not_pr_step.drop(['Process'],axis=1),left_on= 'Word',right_on='Categorization',how='left',suffixes=("","_")).drop('Categorization_',axis=1)
d['Categorization'] = np.where(d['Word_'].notnull(),d['Word'],d['Categorization'])
d['Word'] = np.where(d['Word_'].notnull(),d['Word_'],d['Word'])
d['Definition'] = np.where(d['Word_'].notnull(),d['Definition_'],d['Definition'])
d.drop(['Word_','Definition_'],axis=1,inplace=True)
d

,Process,Categorization,Word,Definition
0,Clustering,Process Step,Goal Setting,Goals of a clustering project can greatly diff...
1,Clustering,Process Step,Goal Setting,"A classification, via calculation utilizing ma..."
2,Clustering,Process Step,Problem Definition,"When choosing, need to have a explicit underst..."
3,Clustering,Process Step,Problem Definition,"Define the intended use, boundaries, and decis..."
4,Clustering,Process Step,Data Collection,Identify and validate the behavioural attribut...
5,Clustering,Process Step,Data Preparation,Ensure Data is Labelled and Categorized.
6,Clustering,Process Step,Data Preparation,"Review Semantic Classifications, insure suffic..."
7,Clustering,Process Step,Exploratory Data Analysis,NaN
8,Clustering,Process Step,Feature Engineering,NaN
9,Clustering,Process Step,Feature Selection,Correlation & Redundancy Analysis. If Greater ...
10,Clustering,Process Step,Feature Selection,Variance & Stability Contribution: Variance In...
11,Clustering,Process Step,Feature Selection,Clustering Sensitivity / Stability Tests\n1. T...
12,Clustering,Process Step,Feature Selection,4. Incremental Value via Feature Importance in...
13,Clustering,Process Step,Feature Selection,Understand the relative contribution and sensi...
14,Clustering,Process Step,Validation/ Model Selection,"Identify and define distinct, stable member ar..."
15,Clustering,Process Step,Training,NaN
16,Clustering,Process Step,Hyperparameter Tuning,NaN
17,Clustering,Model Evaluation,Variance Inflation Factor,\nVariance Inflation Factor a numerical measu...
18,Clustering,Model Evaluation,Inertia,"Quantitative measure used in clustering, parti..."
19,Clustering,Model Evaluation,Davies–Bouldin Index,Internal clustering evaluation metric that mea...
20,Clustering,Model Evaluation,Calinski–Harabasz Index,"Also known as the Variance Ratio Criterion, is..."
21,Clustering,Process Step,Validation,NaN
22,Clustering,Process Step,Model Summarization / Model Interpretability,"Characterize each archetype using clear, inter..."
23,Clustering,Process Step,Model Summarization / Model Interpretability,Design and apply differentiated engagement str...
24,Clustering,Process Step,Deployment,NaN
25,Clustering,Process Step,Monitoring,"Monitor archetype-level outcomes, migration, a..."
26,Clustering,Process Step,"Bias, Fairness, and Ethics",NaN

In [71]:


create_blank_insert_knowledge_base(df,'Clustering','ML Project')

Consideration
Process Step
Model Evaluation

,Process,Categorization,Word,ORDER,DF_VAL,Definition
17,Clustering,Process Step,Goal Setting,1.0,1.0,"A classification, via calculation utilizing ma..."
24,Clustering,Process Step,Problem Definition,2.0,1.0,"When choosing, need to have a explicit underst..."
25,Clustering,Process Step,Problem Definition,2.0,1.0,"Define the intended use, boundaries, and decis..."
6,Clustering,Process Step,Data Collection,3.0,1.0,Identify and validate the behavioural attribut...
7,Clustering,Process Step,Data Preparation,4.0,1.0,Ensure Data is Labelled and Categorized.
8,Clustering,Process Step,Data Preparation,4.0,1.0,"Review Semantic Classifications, insure suffic..."
10,Clustering,Process Step,Exploratory Data Analysis,5.0,1.0,NaN
11,Clustering,Process Step,Feature Engineering,6.0,1.0,NaN
12,Clustering,Process Step,Feature Selection,7.0,1.0,Correlation & Redundancy Analysis. If Greater ...
13,Clustering,Process Step,Feature Selection,7.0,1.0,Variance & Stability Contribution: Variance In...
14,Clustering,Process Step,Feature Selection,7.0,1.0,Clustering Sensitivity / Stability Tests\n1. T...
15,Clustering,Process Step,Feature Selection,7.0,1.0,4. Incremental Value via Feature Importance in...
16,Clustering,Process Step,Feature Selection,7.0,1.0,Understand the relative contribution and sensi...
28,Clustering,Process Step,Validation/ Model Selection,8.0,1.0,"Identify and define distinct, stable member ar..."
26,Clustering,Process Step,Training,9.0,1.0,NaN
18,Clustering,Process Step,Hyperparameter Tuning,10.0,1.0,NaN
20,Clustering,Process Step,Model Evaluation,11.0,1.0,NaN
27,Clustering,Process Step,Validation,12.0,1.0,NaN
21,Clustering,Process Step,Model Summarization / Model Interpretability,13.0,1.0,"Characterize each archetype using clear, inter..."
22,Clustering,Process Step,Model Summarization / Model Interpretability,13.0,1.0,Design and apply differentiated engagement str...
9,Clustering,Process Step,Deployment,14.0,1.0,NaN
23,Clustering,Process Step,Monitoring,15.0,1.0,"Monitor archetype-level outcomes, migration, a..."
5,Clustering,Process Step,"Bias, Fairness, and Ethics",16.0,1.0,NaN
0,NaN,Consideration,Goal Setting,NaN,2.0,"With clustering, the following strategic outco..."
1,NaN,Model Evaluation,Calinski–Harabasz Index,NaN,2.0,"Also known as the Variance Ratio Criterion, is..."
2,NaN,Model Evaluation,Davies–Bouldin Index,NaN,2.0,Internal clustering evaluation metric that mea...
3,NaN,Model Evaluation,Inertia,NaN,2.0,"Quantitative measure used in clustering, parti..."
4,NaN,Model Evaluation,Variance Inflation Factor,NaN,2.0,\nVariance Inflation Factor a numerical measu...
19,NaN,Process Step,Implementation,NaN,2.0,Goals of a clustering project can greatly diff...

In [20]:
df1['Word'].value_counts()

Word
Data Preparation            99
Feature Selection           49
Requirement                 44
Problem Definition          36
Training                    28
                            ..
GammaRegressor               1
FrozenEstimator              1
FixedThresholdClassifier     1
FeatureUnion                 1
Data Set Column Naming       1
Name: count, Length: 482, dtype: int64

In [25]:
df1 = df.merge(df.drop(['Categorization'],axis=1),left_on='Word',right_on='Process',how='left',suffixes=('', '_r'))
df1 = df1.rename(columns={'Word_r':'Step','Definition_r':"Step Details",'Word':"Category"}).drop('Process_r',axis=1)

df1[df1['Process']=='ML Project'].to_excel('test.xlsx')

In [35]:
c_steps = df[df['Process']=='Clustering']['Word'].tolist()

In [36]:
all_steps = df[df['Process']=='ML Project']['Word'].tolist()

In [64]:
process_type = 'ML Project'
process_name = 'Clustering'

base_df = df[df['Process']==process_type].drop('Definition',axis=1).copy()
base_df['ORDER'] = [x for x in range(1,len(base_df)+1)]
base_df['Process'] = process_name
base_df['DF_VAL'] = 1

temp_df = df[df['Process']==process_name]

In [67]:
base_df

,Process,Categorization,Word,ORDER,DF_VAL
0,Clustering,Process Step,Goal Setting,1,1
1,Clustering,Process Step,Problem Definition,2,1
2,Clustering,Process Step,Data Collection,3,1
3,Clustering,Process Step,Data Preparation,4,1
4,Clustering,Process Step,Exploratory Data Analysis,5,1
5,Clustering,Process Step,Feature Engineering,6,1
6,Clustering,Process Step,Feature Selection,7,1
7,Clustering,Process Step,Validation/ Model Selection,8,1
8,Clustering,Process Step,Training,9,1
9,Clustering,Process Step,Hyperparameter Tuning,10,1
10,Clustering,Process Step,Model Evaluation,11,1
11,Clustering,Process Step,Validation,12,1
12,Clustering,Process Step,Model Summarization / Model Interpretability,13,1
13,Clustering,Process Step,Deployment,14,1
14,Clustering,Process Step,Monitoring,15,1
15,Clustering,Process Step,"Bias, Fairness, and Ethics",16,1

In [66]:
temp_df.head(2)

,Process,Categorization,Word,Definition
138,Clustering,Consideration,Goal Setting,"With clustering, the following strategic outco..."
139,Clustering,Process Step,Implementation,Goals of a clustering project can greatly diff...

,Process,Categorization,Word,ORDER,DF_VAL,Definition
17,Clustering,Process Step,Goal Setting,1.0,1.0,"A classification, via calculation utilizing ma..."
24,Clustering,Process Step,Problem Definition,2.0,1.0,"When choosing, need to have a explicit underst..."
25,Clustering,Process Step,Problem Definition,2.0,1.0,"Define the intended use, boundaries, and decis..."
6,Clustering,Process Step,Data Collection,3.0,1.0,Identify and validate the behavioural attribut...
7,Clustering,Process Step,Data Preparation,4.0,1.0,Ensure Data is Labelled and Categorized.
8,Clustering,Process Step,Data Preparation,4.0,1.0,"Review Semantic Classifications, insure suffic..."
10,Clustering,Process Step,Exploratory Data Analysis,5.0,1.0,NaN
11,Clustering,Process Step,Feature Engineering,6.0,1.0,NaN
12,Clustering,Process Step,Feature Selection,7.0,1.0,Correlation & Redundancy Analysis. If Greater ...
13,Clustering,Process Step,Feature Selection,7.0,1.0,Variance & Stability Contribution: Variance In...
14,Clustering,Process Step,Feature Selection,7.0,1.0,Clustering Sensitivity / Stability Tests\n1. T...
15,Clustering,Process Step,Feature Selection,7.0,1.0,4. Incremental Value via Feature Importance in...
16,Clustering,Process Step,Feature Selection,7.0,1.0,Understand the relative contribution and sensi...
28,Clustering,Process Step,Validation/ Model Selection,8.0,1.0,"Identify and define distinct, stable member ar..."
26,Clustering,Process Step,Training,9.0,1.0,NaN
18,Clustering,Process Step,Hyperparameter Tuning,10.0,1.0,NaN
20,Clustering,Process Step,Model Evaluation,11.0,1.0,NaN
27,Clustering,Process Step,Validation,12.0,1.0,NaN
21,Clustering,Process Step,Model Summarization / Model Interpretability,13.0,1.0,"Characterize each archetype using clear, inter..."
22,Clustering,Process Step,Model Summarization / Model Interpretability,13.0,1.0,Design and apply differentiated engagement str...
9,Clustering,Process Step,Deployment,14.0,1.0,NaN
23,Clustering,Process Step,Monitoring,15.0,1.0,"Monitor archetype-level outcomes, migration, a..."
5,Clustering,Process Step,"Bias, Fairness, and Ethics",16.0,1.0,NaN
0,NaN,Consideration,Goal Setting,NaN,2.0,"With clustering, the following strategic outco..."
1,NaN,Model Evaluation,Calinski–Harabasz Index,NaN,2.0,"Also known as the Variance Ratio Criterion, is..."
2,NaN,Model Evaluation,Davies–Bouldin Index,NaN,2.0,Internal clustering evaluation metric that mea...
3,NaN,Model Evaluation,Inertia,NaN,2.0,"Quantitative measure used in clustering, parti..."
4,NaN,Model Evaluation,Variance Inflation Factor,NaN,2.0,\nVariance Inflation Factor a numerical measu...
19,NaN,Process Step,Implementation,NaN,2.0,Goals of a clustering project can greatly diff...

In [54]:
a

,Process,Categorization,Word,RANK
0,Clustering,Process Step,Goal Setting,1
1,Clustering,Process Step,Problem Definition,2
2,Clustering,Process Step,Data Collection,3
3,Clustering,Process Step,Data Preparation,4
4,Clustering,Process Step,Exploratory Data Analysis,5
5,Clustering,Process Step,Feature Engineering,6
6,Clustering,Process Step,Feature Selection,7
7,Clustering,Process Step,Validation/ Model Selection,8
8,Clustering,Process Step,Training,9
9,Clustering,Process Step,Hyperparameter Tuning,10
10,Clustering,Process Step,Model Evaluation,11
11,Clustering,Process Step,Validation,12
12,Clustering,Process Step,Model Summarization / Model Interpretability,13
13,Clustering,Process Step,Deployment,14
14,Clustering,Process Step,Monitoring,15
15,Clustering,Process Step,"Bias, Fairness, and Ethics",16

In [47]:
b

,Process,Categorization,Word,Definition
138,Clustering,Consideration,Goal Setting,"With clustering, the following strategic outco..."
139,Clustering,Process Step,Implementation,Goals of a clustering project can greatly diff...
140,Clustering,Process Step,Goal Setting,"A classification, via calculation utilizing ma..."
141,Clustering,Process Step,Problem Definition,"When choosing, need to have a explicit underst..."
142,Clustering,Process Step,Problem Definition,"Define the intended use, boundaries, and decis..."
143,Clustering,Process Step,Data Collection,Identify and validate the behavioural attribut...
144,Clustering,Process Step,Data Preparation,Ensure Data is Labelled and Categorized.
145,Clustering,Process Step,Data Preparation,"Review Semantic Classifications, insure suffic..."
146,Clustering,Process Step,Feature Selection,Correlation & Redundancy Analysis. If Greater ...
147,Clustering,Process Step,Feature Selection,Variance & Stability Contribution: Variance In...
148,Clustering,Process Step,Feature Selection,Clustering Sensitivity / Stability Tests\n1. T...
149,Clustering,Process Step,Feature Selection,4. Incremental Value via Feature Importance in...
150,Clustering,Process Step,Feature Selection,Understand the relative contribution and sensi...
151,Clustering,Process Step,Validation/ Model Selection,"Identify and define distinct, stable member ar..."
152,Clustering,Process Step,Model Summarization / Model Interpretability,"Characterize each archetype using clear, inter..."
153,Clustering,Process Step,Model Summarization / Model Interpretability,Design and apply differentiated engagement str...
154,Clustering,Process Step,Monitoring,"Monitor archetype-level outcomes, migration, a..."
155,Clustering,Model Evaluation,Variance Inflation Factor,\nVariance Inflation Factor a numerical measu...
156,Clustering,Model Evaluation,Inertia,"Quantitative measure used in clustering, parti..."
157,Clustering,Model Evaluation,Davies–Bouldin Index,Internal clustering evaluation metric that mea...
158,Clustering,Model Evaluation,Calinski–Harabasz Index,"Also known as the Variance Ratio Criterion, is..."

In [37]:
[x for x in all_steps if x not in c_steps]

['Exploratory Data Analysis',
 'Feature Engineering',
 'Training',
 'Hyperparameter Tuning',
 'Model Evaluation',
 'Validation',
 'Deployment',
 'Bias, Fairness, and Ethics']

In [ ]:
 #APPLY ML STRUCTURE

In [ ]:
def create_process_dataframe(df):
    '''
    
    
    '''

    d

In [26]:
df1[df1['Process']=='Clustering']

,Process,Categorization,Category,Definition,Step,Step Details
235,Clustering,Consideration,Goal Setting,"With clustering, the following strategic outco...",Specific,Describes what will be accomplished and what s...
236,Clustering,Consideration,Goal Setting,"With clustering, the following strategic outco...",Measurable,Includes a clear way to track progress or dete...
237,Clustering,Consideration,Goal Setting,"With clustering, the following strategic outco...",Achievable,"Realistic given available time, resources, ski..."
238,Clustering,Consideration,Goal Setting,"With clustering, the following strategic outco...",Relevant,"Aligns with broader priorities, such as team o..."
239,Clustering,Consideration,Goal Setting,"With clustering, the following strategic outco...",Time Bound,Includes a clear deadline or timeframe for com...
...,...,...,...,...,...,...
378,Clustering,Process Step,Monitoring,"Monitor archetype-level outcomes, migration, a...",Requirement,Define triggers for retraining or model review...
379,Clustering,Model Evaluation,Variance Inflation Factor,\nVariance Inflation Factor a numerical measu...,NaN,NaN
380,Clustering,Model Evaluation,Inertia,"Quantitative measure used in clustering, parti...",NaN,NaN
381,Clustering,Model Evaluation,Davies–Bouldin Index,Internal clustering evaluation metric that mea...,NaN,NaN
382,Clustering,Model Evaluation,Calinski–Harabasz Index,"Also known as the Variance Ratio Criterion, is...",NaN,NaN

In [8]:
df[df['Process']=='Goal Setting']

,Process,Categorization,Word,Definition
16,Goal Setting,Process Step,Specific,Describes what will be accomplished and what s...
17,Goal Setting,Process Step,Measurable,Includes a clear way to track progress or dete...
18,Goal Setting,Process Step,Achievable,"Realistic given available time, resources, ski..."
19,Goal Setting,Process Step,Relevant,"Aligns with broader priorities, such as team o..."
20,Goal Setting,Process Step,Time Bound,Includes a clear deadline or timeframe for com...
21,Goal Setting,Process Step,Requirement,"Are Goals Documented. Are the Smart.\nIf not, ..."

In [7]:
df[df['Process']=='ML Project']

,Process,Categorization,Word,Definition
0,ML Project,Process Step,Goal Setting,"Establish a clear, concise and explicit goal f..."
1,ML Project,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
2,ML Project,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
3,ML Project,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...
4,ML Project,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...
5,ML Project,Process Step,Feature Engineering,Process of creating new input variables that b...
6,ML Project,Process Step,Feature Selection,Process of identifying and retaining the most ...
7,ML Project,Process Step,Validation/ Model Selection,The process of choosing the most appropriate a...
8,ML Project,Process Step,Training,Process of fitting a machine learning model to...
9,ML Project,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...
10,ML Project,Process Step,Model Evaluation,Process of measuring how well a trained model ...
11,ML Project,Process Step,Validation,Validation is the process of assessing model p...
12,ML Project,Process Step,Model Summarization / Model Interpretability,Process of explaining how a model makes predic...
13,ML Project,Process Step,Deployment,Deployment is the process of integrating the t...
14,ML Project,Process Step,Monitoring,Ongoing process of tracking model performance ...
15,ML Project,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...