In [3]:
import pandas as pd
import numpy as np
import datetime
import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")
from filesystem_tools import parse_dot_py_folder

In [11]:
import os
os.getcwd()

'/Users/derekdewald/Documents/Python/Github_Repo/JupyterNotebooks'

In [9]:
df = pd.read_excel('knowledge_base.xlsx')
df

,Process,Categorization,Word,Definition
0,Behavioural Economics,Information,Fact Believability,Facts about this epidemic that have lasted a f...
1,Behavioural Economics,Information,Facts Vs Statistics,More likely to die in accident in evening than...
2,Behavioural Economics,Information,Organizations,Great at solving Problems. Bad at diagnosing ...
3,Behavioural Economics,Information,Think about the Medium,"Weekly, daily, hourly—the metronome of the new..."
4,Behavioural Economics,Information,Unintended Consequences KPIs,Must consider what adverse effects one might c...
...,...,...,...,...
213,Process Values Currently in Use,Reference List,Model Evaluation,Process of measuring how well a trained model ...
214,Process Values Currently in Use,Reference List,Notes,NaN
215,Process Values Currently in Use,Reference List,Problem Definition,"A Clear, Concise and explicit definition of th..."
216,Process Values Currently in Use,Reference List,Problem Solving Framework,NaN
217,Process Values Currently in Use,Reference List,Statistics,NaN

In [10]:
from daily_etl_folder_mgmt import generate_knowledgebase

#################### ADD EXCEL MANDATORY WITH FORCE FALSE.

df1 = generate_knowledgebase()
df1

,Process,Categorization,Word,Definition
120,Behavioural Economics,Concept,Anchoring Effect,A cognitive bias where people rely too heavily...
121,Behavioural Economics,Concept,Base Rate Fallacy,People ignore or undervalue general statistica...
123,Behavioural Economics,Concept,Biased Assimilation,Tendency to interpret information in a way tha...
124,Behavioural Economics,Concept,Blind spot bias,Cognitive bias where people are unaware of the...
122,Behavioural Economics,Concept,Bureaucratic Politics,Organization decision making paradigm in which...
...,...,...,...,...
232,Process Values Currently in Use,Reference List,Model Evaluation,Process of measuring how well a trained model ...
238,Process Values Currently in Use,Reference List,Notes,NaN
228,Process Values Currently in Use,Reference List,Problem Definition,"A Clear, Concise and explicit definition of th..."
239,Process Values Currently in Use,Reference List,Problem Solving Framework,NaN
233,Process Values Currently in Use,Reference List,Statistics,NaN

In [7]:
from filesystem_tools import print_python_str_template

print_python_str_template()

Definition:
	Definition
Parameters:
	Definition
Returns:
	Definition
Date Created:
	06-Jul-26
Date Last Modified:
	06-Jul-26
Process:
	Definition
Categorization:
	Definition
Usage:
	Definition
Notes:
	Definition

In [4]:
function_list,parameter_list = parse_dot_py_folder(export_location='/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/')

python_function_list Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/
python_function_parameters Saved to /Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/

In [3]:
function_list

,Function,Definition,Parameters,Returns,Date Created,Date Last Modified,Process,Categorization,Usage,Notes,Folder
0,read_directory,Function which reads reads a directory and ret...,"[location, file_type, match_str]",Dataframe,3-Dec-25,3-Dec-25,ETL,File Manipulation/ Management,d_py_function = '/Users/derekdewald/Documents...,NaN,filesystem_tools.py
1,txt_to_python,Function Used to Import .txt or .py File into ...,"[file_name, encoding]",Dataframe,3-Dec-25,3-Dec-25,ETL,File Manipulation/ Management,location = '/Users/derekdewald/Documents/Pytho...,NaN,filesystem_tools.py
2,print_python_str_template,Display default python documentation string in...,[object_dict],Console Text,06-Jul-26,06-Jul-26,Documentation,Python String Documentation,print_python_str_template(),,filesystem_tools.py
3,parse_dot_py_file,Function which parses a .py file which has bee...,"[file_text, function_columns]",Excel File(s),05-Aug-25,06-Jul-26,Documentation,TBD,location = '/Users/derekdewald/Documents/Pytho...,Update on 6-Jul-26 included generalization of ...,filesystem_tools.py
4,parse_dot_py_folder,Function which sacles parse_dot_py_file to fol...,"[location, export_location]",DataFrame(s),4-Dec-25,06-Jul-26,Documentation,Python String Documentation,parse_dot_py_folder(),Definition,filesystem_tools.py
0,extract_consolidated_raw_dataset,Create a Consolidated Dataset of files in Dict...,"[df_dict, export_location]",Excel File,06-Jul-26,06-Jul-26,ETL,Excel File Creation,"df_dict = {\n'Notes':notes_df,\n'Definitions':...",Definition,daily_etl_folder_mgmt.py
1,generate_objects_automated_py,Create Automated Python File,"[links_df, consolidated_df]",Dot Py File,29-Jun-26,29-Jun-26,Documentation,Manual File Creator,"generate_objects_automated_py(links_df,consoli...",Definition,daily_etl_folder_mgmt.py
2,extract_object_dot_py,Generate an Excel file of all parameters which...,"[object_dict, export_location]",DataFrame,29-Jun-26,03-Jul-26,Documentation,Excel File Creator,from objects_manual import object_dict as manu...,"Jul Update. Added Definition as new record, ad...",daily_etl_folder_mgmt.py
3,generate_knowledgebase,Process Utilized to Combine Notes/ Definitions...,"[notes_df, definition_df, manual_object_df, au...",Excel File,02-Jul-26,02-Jul-26,Definition,Definition,"d = generate_knowledgebase(notes_df,definition...",None,daily_etl_folder_mgmt.py

In [6]:
parameter_list

,Folder,Function,Parameters,Type,Definition
0,filesystem_tools.py,read_directory,location,str,The path to the directory. Defaults to the cur...
1,filesystem_tools.py,read_directory,file_type,str,"The file extension or type to filter by (e.g.,..."
2,filesystem_tools.py,read_directory,match_str,str,Option to be applied to help filter only wante...
3,filesystem_tools.py,txt_to_python,file_name,str,"Name of File, including path location for import"
4,filesystem_tools.py,txt_to_python,encoding,str,Encoding to be applied by With Open call. Defa...
5,filesystem_tools.py,print_python_str_template,object_dict,list,List of Default Parameters to be iterated thro...
6,filesystem_tools.py,parse_dot_py_file,file_text,str,"Text, which should be structured someone in fo..."
7,filesystem_tools.py,parse_dot_py_file,function_columns,list,List of columns to include in output file and ...
8,filesystem_tools.py,parse_dot_py_folder,location,str,Location of Folder to be read for .py files. D...
9,filesystem_tools.py,parse_dot_py_folder,export_location,str,Location to where CSV file is to be exported. ...
0,daily_etl_folder_mgmt.py,extract_consolidated_raw_dataset,df_dict,dict,Dictionary of files to be included.
1,daily_etl_folder_mgmt.py,extract_consolidated_raw_dataset,export_location,str,Location to where CSV file is to be exported. ...
2,daily_etl_folder_mgmt.py,generate_objects_automated_py,links_df,df,Data from Google Sheets with Location of CSV a...
3,daily_etl_folder_mgmt.py,generate_objects_automated_py,consolidated_df,df,Dataset created from extract_consolidated_raw_...
4,daily_etl_folder_mgmt.py,extract_object_dot_py,object_dict,dict,Dictionary Object from either objects_manual o...
5,daily_etl_folder_mgmt.py,extract_object_dot_py,export_location,str,Location where .xlsx file will be saved.
6,daily_etl_folder_mgmt.py,generate_knowledgebase,notes_df,dataframe,Dataframe containing Notes from Google. Defaul...
7,daily_etl_folder_mgmt.py,generate_knowledgebase,definition_df,dataframe,Dataframe containing Definitions from Google. ...
8,daily_etl_folder_mgmt.py,generate_knowledgebase,manual_object_df,dataframe,Dataframe containining Dataframe of Parameters...
9,daily_etl_folder_mgmt.py,generate_knowledgebase,auto_object_df,,
10,daily_etl_folder_mgmt.py,generate_knowledgebase,export_location,str,Name of File to export excel file to. If Blank...

In [4]:
import os
os.getcwd()
os.listdir('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data')

['.DS_Store',
 'consolidated_dataset.xlsx',
 'knowledge_base.xlsx',
 'object_auto_published.xlsx',
 'defined_processes.xlsx',
 'object_manual_published.xlsx']

In [ ]:
# Want to Bring Functions which Pull .py script into New Environment, so I can consistently Name Functions.
# I want to also Automate Definitions for Classification and Process.D


# How to Document Where A File/Table is Being Made or that a File Exists????


# How do I want test when I make a change?

In [2]:
## How to Generate Documentation for Python .
## How can I make it useful.

In [2]:
location = '/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions/'
file_text = txt_to_python(f"{location}/filesystem_tools.py")

from filesystem_tools import parse_dot_py_file

a,b = parse_dot_py_file(file_text)

In [5]:
a

,Function,Definition,Parameters,Returns,Date Created,Date Last Modified,Process,Categorization,Usage,Notes
0,read_directory,Function which reads reads a directory and ret...,"[location, file_type, match_str]",Dataframe,3-Dec-25,3-Dec-25,ETL,File Manipulation/ Management,d_py_function = '/Users/derekdewald/Documents...,NaN
1,txt_to_python,Function Used to Import .txt or .py File into ...,"[file_name, encoding]",Dataframe,3-Dec-25,3-Dec-25,ETL,File Manipulation/ Management,location = '/Users/derekdewald/Documents/Pytho...,NaN
2,print_python_str_template,Display default python documentation string in...,[object_dict],Console Text,06-Jul-26,06-Jul-26,Documentation,Python String Documentation,print_python_str_template(),
3,parse_dot_py_file,Function which parses a .py file which has bee...,"[file_text, function_columns]",Excel File(s),05-Aug-25,06-Jul-26,Documentation,TBD,location = '/Users/derekdewald/Documents/Pytho...,Update on 6-Jul-26 included generalization of ...

In [7]:
function_list

,Function,Definition,Parameters,Returns,Date Created,Date Last Modified,Process,Categorization,Usage,Notes,Folder
0,read_directory,Function which reads reads a directory and ret...,"[location, file_type, match_str]",Dataframe,3-Dec-25,3-Dec-25,ETL,File Manipulation/ Management,d_py_function = '/Users/derekdewald/Documents...,NaN,filesystem_tools.py
1,txt_to_python,Function Used to Import .txt or .py File into ...,"[file_name, encoding]",Dataframe,3-Dec-25,3-Dec-25,ETL,File Manipulation/ Management,location = '/Users/derekdewald/Documents/Pytho...,NaN,filesystem_tools.py
2,print_python_str_template,Display default python documentation string in...,[object_dict],Console Text,06-Jul-26,06-Jul-26,Documentation,Python String Documentation,print_python_str_template(),,filesystem_tools.py
3,parse_dot_py_file,Function which parses a .py file which has bee...,"[file_text, function_columns]",Excel File(s),05-Aug-25,06-Jul-26,Documentation,TBD,location = '/Users/derekdewald/Documents/Pytho...,Update on 6-Jul-26 included generalization of ...,filesystem_tools.py
0,extract_consolidated_raw_dataset,None,"[df_dict, export_location]",Dataframe date_created:03-Jul-26 date_last_mod...,None,None,None,None,"df_dict = {\n'Notes':notes_df,\n'Definitions':...",None,daily_etl_folder_mgmt.py
1,generate_objects_automated_py,None,"[links_df, consolidated_df]",Object Type date_created:29-Jun-26 date_last_m...,None,None,None,None,"generate_objects_automated_py(links_df,consoli...",None,daily_etl_folder_mgmt.py
2,extract_object_dot_py,None,"[object_dict, export_location]",df date_created:29-Jun-26 date_last_modified: ...,None,None,None,None,"manual_object_df(object_dict_manual,'/Users/de...",None,daily_etl_folder_mgmt.py
3,generate_knowledgebase,None,"[notes_df, definition_df, manual_object_df, au...",dataframe excel_file date_created:02-Jul-26 da...,None,None,None,None,"d = generate_knowledgebase(notes_df,definition...",None,daily_etl_folder_mgmt.py

In [8]:
function_parameters

,Folder,Function,Parameters,Type,Definition
0,filesystem_tools.py,read_directory,location,str,The path to the directory. Defaults to the cur...
1,filesystem_tools.py,read_directory,file_type,str,"The file extension or type to filter by (e.g.,..."
2,filesystem_tools.py,read_directory,match_str,str,Option to be applied to help filter only wante...
3,filesystem_tools.py,txt_to_python,file_name,str,"Name of File, including path location for import"
4,filesystem_tools.py,txt_to_python,encoding,str,Encoding to be applied by With Open call. Defa...
5,filesystem_tools.py,print_python_str_template,object_dict,list,List of Default Parameters to be iterated thro...
6,filesystem_tools.py,parse_dot_py_file,file_text,str,"Text, which should be structured someone in fo..."
7,filesystem_tools.py,parse_dot_py_file,function_columns,list,List of columns to include in output file and ...
0,daily_etl_folder_mgmt.py,extract_consolidated_raw_dataset,df_dict,dict,Dictionary of files to be included.
1,daily_etl_folder_mgmt.py,extract_consolidated_raw_dataset,export_location,,
2,daily_etl_folder_mgmt.py,generate_objects_automated_py,links_df,df,Data from Google Sheets with Location of CSV a...
3,daily_etl_folder_mgmt.py,generate_objects_automated_py,consolidated_df,df,Dataset created from extract_consolidated_raw_...
4,daily_etl_folder_mgmt.py,extract_object_dot_py,object_dict,dict,Dictionary Object from either objects_manual o...
5,daily_etl_folder_mgmt.py,extract_object_dot_py,export_location,str,Location where .xlsx file will be saved.
6,daily_etl_folder_mgmt.py,generate_knowledgebase,notes_df,dataframe,Dataframe containing Notes from Google. Defaul...
7,daily_etl_folder_mgmt.py,generate_knowledgebase,definition_df,dataframe,Dataframe containing Definitions from Google. ...
8,daily_etl_folder_mgmt.py,generate_knowledgebase,manual_object_df,dataframe,Dataframe containining Dataframe of Parameters...
9,daily_etl_folder_mgmt.py,generate_knowledgebase,auto_object_df,,
10,daily_etl_folder_mgmt.py,generate_knowledgebase,export_location,str,Name of File to export excel file to. If Blank...

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np
import shutil
import ast
import os
import re


# Import Location of D Python Functions
import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

from dict_processing import dict_to_dataframe
from list_processing import list_to_dataframe
import data_d_dicts, data_d_lists,data_d_strings
from data_d_lists import function_fields
from input_functions_ignore import input1,input2,input3







def move_file_in_folder(folder1,
                        folder2,
                        file_name,
                        overwrite_without_validation=False
                       ):
    
    '''
    Function Created to Help Move Files Between Folders Directly in Python.
    Function will validate that the Folders both exist and there currently isn't a file of the same name, to reduce risk of overwriting
    unexpectedly. (There is a manual override).

    Parameters:
        folder1(str): Folder of First File
        folder2(str): Folder of Second File
        file_name(str): Name of File to be moved, does not matter of file type)
        overwrite_without_validation(bool): Optional Argument allowing user to automate by apply to default overwrite (also meant to help
        reduce risk of losting information due to inadvertent overwriting)

    Returns:
        None

    date_created:09-Feb-26
    date_last_modified: 09-Feb-26
    classification:TBD
    sub_classification:TBD
    usage:
        
        folder1 = '/Users/derekdewald/Documents/Python/Github_Repo/JupyterNotebooks'
        folder2 = '/Users/derekdewald/Documents/Python/Github_Repo/Project Folder/Synthetic Member Dataset'

        move_file_in_folder(folder1,folder2,'Sythentic Member V3.ipynb')

     

    
    '''

    # Check if Path 1 exists.
    # Check if Path 2 Exists.
    # Check if File Exists in Path 1
    # Check if Files Exists in Path 2 (do not want to overwrite)


    folder1 = Path(folder1)
    folder2 = Path(folder2)

    src_file = folder1 / file_name
    dst_file = folder2 / file_name

    # Check if source folder exists
    if not folder1.exists():
        return f"Source folder does not exist: {folder1}"

    # Check if destination folder exists
    if not folder2.exists():
        return f"Destination folder does not exist: {folder2}"

    # Check if file exists in source
    if not src_file.exists():
        return f"File not found in source folder: {src_file}"

    # Check if file exists in destination
    if dst_file.exists():
        if overwrite_without_validation:
            dst_file.unlink()  # remove existing file
        else:
            return f"File already exists in destination: {dst_file}"

    # Move the file
    shutil.move(str(src_file), str(dst_file))

    return f"File moved successfully: {file_name}"