In [59]:
%history -f text.txt

In [ ]:
## USE PROCESS: CATEGORIZATION. CATEGFORIATION: DEFINITION WORD: Metric as an example.
# How to get Optimization and Loss Functions.
# Update ML to have all Parameters?

In [1]:
import pandas as pd
import numpy as np
import datetime

import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

from objects_automated import object_dict

### Local Files

In [2]:
consolidated_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/consolidated_dataset.xlsx')
knowledge_base_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/knowledge_base.xlsx')

### Google Sheets

In [ ]:
link_df = pd.read_csv(object_dict['csv_links']['python_object']['d_links'])
notes_df = pd.read_csv(object_dict['csv_links']['python_object']['google_notes_csv'])
definition_df = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])
technical_notes = pd.read_csv(object_dict['csv_links']['python_object']['technical_notes'])

In [5]:
knowledge_base_df.head()

,Process,Categorization,Word,Definition
0,Behavioural Economics,Information,Fact Believability,Facts about this epidemic that have lasted a f...
1,Behavioural Economics,Information,Facts Vs Statistics,More likely to die in accident in evening than...
2,Behavioural Economics,Information,Organizations,Great at solving Problems. Bad at diagnosing ...
3,Behavioural Economics,Information,Think about the Medium,"Weekly, daily, hourly—the metronome of the new..."
4,Behavioural Economics,Information,Unintended Consequences KPIs,Must consider what adverse effects one might c...

In [4]:
definition_df.head(1)

,Process,Categorization,Word,Definition,Notes,Link,Image,Markdown Equation,Dataset Size,Learning Type,Algorithm Classification,Model Type
0,Behavioural Economics,Concept,Anchoring Effect,A cognitive bias where people rely too heavily...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
def missing_processes_from_knowledgebase(knowledge_base_df,definition_df):

    temp_df = definition_df[['Process','Categorization','Word',"Definition"]].copy()

    kb_temp = knowledge_base_df[['Process']].drop_duplicates().reset_index(drop=True)
    kb_temp['PROC_IN_KNOWLEDGE_BASE']= 1

    kb_temp1 = knowledge_base_df[['Word']].drop_duplicates().reset_index(drop=True)
    kb_temp1['WORD_IN_KNOWLEDGE_BASE']= 1

    temp_df = temp_df.merge(kb_temp,on='Process',how='left').merge(kb_temp1,on='Word',how='left').fillna(0)

    return temp_df

d = missing_processes_from_knowledgebase(knowledge_base_df,definition_df)

d[d['PROC_IN_KNOWLEDGE_BASE']==0]['Process'].value_counts()

Process
TBD                                        508
Mathematics                                 23
Generative Models                           22
General Definition                          17
Method Objective                            15
Representation Learning                     15
Information Retrieval                       14
Spark                                       12
Confusion Matrix                            12
Hyperparameter                              12
Kubernetes PE                               11
Dot Py String Classification                10
Wicked Problem                              10
Method Approach                             10
What Problem are we Trying to Solve?        10
Graph Algorithms                             9
Function                                     8
Time Series Forecasting                      8
Reinforcement Learning                       8
Optimization Function                        7
Classification                               5
Anomaly Detection                            5
Regression                                   5
Ranking / Recommendation                     5
Density Estimation                           5
Dimensionality Reduction                     5
Feature Transformation                       5
Activation Function                          5
Graph Theory                                 5
AI Agents                                    5
How is the Answer to a Problem Obtained      5
Statistics                                   4
Organization Taxonomy                        4
Supervised Learning                          4
ML Model Taxonomy                            4
Learning Paradigm                            4
Method                                       4
Principle                                    4
Retrieval Augmentation Generation            4
ML Training                                  3
Neural Network                               3
LLM                                          3
Similarity                                   3
Categorization                               2
Loss Function                                2
Vector Search                                1
Vector Database                              1
NLP                                          1
Hadoop                                       1
Decison Making                               1
Natural Language Processing                  1
Langchain                                    1
Nonlinear Models                             1
Name: count, dtype: int64

In [ ]:
auto_object_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_auto_published.xlsx')
manual_object_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx')

In [ ]:
# I do not want to Bring Automated. It's confusing and causes Duplication. 
# I want to insure that Every Process from Definition Is Included.


# I should be able to Manage Everything from Notes.

# Process.
# Categorization - All Process Steps should be retained in Definition. Along with an Explanation as to what that process is.
# Word
# Definition. 

# Everything Should Have a Master Process.

In [78]:
test_df = pd.concat([definition_df,notes_df])
test_df

,Process,Categorization,Word,Definition
0,Behavioural Economics,Concept,Anchoring Effect,A cognitive bias where people rely too heavily...
1,Behavioural Economics,Concept,Base Rate Fallacy,People ignore or undervalue general statistica...
2,Behavioural Economics,Concept,Bureaucratic Politics,Organization decision making paradigm in which...
3,Behavioural Economics,Concept,Biased Assimilation,Tendency to interpret information in a way tha...
4,Behavioural Economics,Concept,Blind spot bias,Cognitive bias where people are unaware of the...
...,...,...,...,...
210,Tree Based Models,Guiding Principle,Feature Selection,Feature importance in a tree based model is ba...
211,Tree Based Models,Guiding Principle,Feature Selection,Because a feature has a low feature importance...
212,Tree Based Models,Guiding Principle,Feature Selection,Standardized vs Non Standardized in interpreti...
213,Presentation Tenants,TBD,What Am I looking at.,The bigger display with a wider array of jams ...
214,Presentation Tenants,TBD,NaN,When someone tells a joke poorly it is more li...

In [76]:
definition_df['Process'].value_counts()

Process
TBD                            508
Data Preparation                35
Mathematics                     23
Generative Models               22
General Definition              17
                              ...
Decison Making                   1
Natural Language Processing      1
Langchain                        1
Nonlinear Models                 1
Exploratory Data Analysis        1
Name: count, Length: 65, dtype: int64

In [ ]:

def generate_knowledgebase(
    notes_df=pd.DataFrame(),
    definition_df=pd.DataFrame(),
    manual_object_df=pd.DataFrame(),
    auto_object_df=pd.DataFrame(),
    export_location=None):

    '''
    Definition:
        Process Utilized to Combine Notes/ Definitions and Logic into Knowledge Base, which is utilized to Create, Processes, Parameters.
    Parameters:
        notes_df (dataframe): Dataframe containing Notes from Google. Default is none and it will pull directly from Google.
        definition_df (dataframe): Dataframe containing Definitions from Google. Default is none and it will pull directly from Google.
        manual_object_df (dataframe): Dataframe containining Dataframe of Parameters, generated from Python Process _____, which converts lists in objects_manual.py.
        export_location(str): Name of File to export excel file to. If Blank, returns nothing
    Returns:
        Excel File
    Date Created:
        02-Jul-26
    Date Last Modified:
        22-Jul-26
    Process:
        Definition
    Categorization:
        Definition
    Usage:
        d = generate_knowledgebase(notes_df,definition_df,manual_object_df)
        d = generate_knowledgebase()
    Notes:
        22-Jul - Overhauled merge. Attempted to streamline, simplify and reduce duplication. Increase Visability.
        
    '''
    
    if len(notes_df)==0:
        notes_df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vSQF2lNc4WPeTRQ_VzWPkqSZp4RODFkbap8AqmolWp5bKoMaslP2oRVVG21x2POu_JcbF1tGRcBgodu/pub?output=csv')
        notes_df = notes_df[notes_df['Word'].notnull()].copy()

    if len(definition_df)==0:
        definition_df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQq1-3cTas8DCWBa2NKYhVFXpl8kLaFDohg0zMfNTAU_Fiw6aIFLWfA5zRem4eSaGPa7UiQvkz05loW/pub?output=csv')
        definition_df = definition_df[definition_df['Word'].notnull()].copy()
    if len(auto_object_df)==0:
        auto_object_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_auto_published.xlsx')
        auto_object_df = auto_object_df[auto_object_df['Word'].notnull()].copy()

    if len(manual_object_df)==0:
        manual_object_df = pd.read_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx')
        manual_object_df = manual_object_df[manual_object_df['Word'].notnull()].copy()

    # Combine Notes from Google and Notes Extract from Manual List
    consolidated_notes = pd.concat([notes_df,manual_object_df.drop('Order',axis=1)])

    # Take all Processes from Notes, so we can extract Definitions
    process_list = consolidated_notes['Process'].unique().tolist()

    # Also, include any Item in the Consolidated sheet that is a Process Step. 
    process_list.extend(consolidated_notes[consolidated_notes['Categorization']=='Process Step']['Word'].unique().tolist())
    process_list = list(set(process_list))

    # Extract Definitions to include into Consolidated Notes.
    notes_from_def = definition_df[definition_df['Process'].isin(process_list)][['Process','Categorization','Word','Definition']]
    
    # Create a Consolidated notes list (Before Incorporating Definitions).
    
    final_df = pd.concat([
        consolidated_notes,
        notes_from_def])

    # Merge in Definitions.
    final_df1 = final_df.merge(definition_df[['Word','Definition']].drop_duplicates('Word'),on='Word',how='left',suffixes=("","_"))
    final_df1['Definition'] = np.where(final_df1['Definition'].isnull(),final_df1['Definition_'],final_df1['Definition'])
    final_df1.drop('Definition_',axis=1,inplace=True)

    # Merge in Processes into themself. IE. In Machine Learning Lifecycle add Goal Setting Steps to makea  complete process
    temp = final_df1[final_df1['Process'].isin(final_df1['Word'].tolist())].copy()
    temp['Categorization'] = temp['Process'].copy()

    # Add this as we will use it at the very end after filtering has been completed.
    temp['Word__'] = temp['Word'].copy()
    temp['Word'] = temp['Process'].copy()
    temp.drop(['Process','Categorization'],axis=1,inplace=True)

    # Need to create a distinct dataset with which to merge into.    
    temp1 = final_df1.merge(temp,on='Word',how='inner',suffixes=("","_"))
    temp1['Categorization'] = temp1['Word'].copy()
    temp1['Definition'] = np.where(temp1['Definition_'].notnull(),temp1['Definition_'],temp1['Definition'])
    temp1.drop('Definition_',axis=1,inplace=True)
    
    final_df1 = pd.concat([final_df1,temp1])
        
    auto_object_df = auto_object_df.merge(definition_df[['Word','Definition']].drop_duplicates('Word'),on='Word',how='left',suffixes=("","_"))
    auto_object_df['Definition'] = np.where(auto_object_df['Definition'].isnull(),auto_object_df['Definition_'],auto_object_df['Definition'])
    auto_object_df.drop('Definition_',inplace=True,axis=1)
    
    # Add Automated Dictionary. Here, do not want it causing duplication/ Issue.
    final_df1 = pd.concat([
        final_df1,
        auto_object_df
    ])

    # Sorting
    # Process - Has to be Alphabetical. Do not actually Care Order.
    # Categorization - Based on Manually defined Order, imported from Objects_Manual.
    # Words Matter when they are part of a process, generally when not then alphabetically preferred. 
    
    # Merge in Process  Filter
    cat_filter = cat_filter = manual_object_df[manual_object_df['Process']=='Categorization Filter Order'][["Word",'Order']].reset_index(drop=True).rename(columns={'Word':"Categorization",'Order':"proc_order"})
    final_df1 = final_df1.merge(cat_filter,on='Categorization',how='left')
    
    # Merge in Word Order.
    final_df1 = final_df1.merge(manual_object_df.drop(['Categorization','Definition'],axis=1).rename(columns={'Order':'word_order'}),on=['Process','Word'],how='left')

    # Merge in ML Lifecycle Order to filter Category for instances where No other filter is being applied
    ml_order = manual_object_df[manual_object_df['Process']=='Machine Learning Lifecycle'][['Word','Order']].rename(columns={'Order':"ml_order"})
    
    final_df1 = final_df1.merge(ml_order,on='Word',how='left')
    final_df1 = final_df1.merge(ml_order.rename(columns={'ml_order':'ml1_order','Word':"Categorization"}),on='Categorization',how='left')
    
    final_df1.sort_values(['Process','word_order','proc_order','ml_order','ml1_order','Categorization','Word'],inplace=True)

    final_df1['Word'] = np.where(final_df1['Word__'].notnull(),final_df1['Word__'],final_df1['Word'])
    
    final_df1.drop(['word_order','proc_order','Word__','ml_order','ml1_order'],axis=1,inplace=True)    
    final_df1.reset_index(drop=True,inplace=True)

    if export_location:
        final_df1.to_excel(export_location,index=False)
       
    return final_df1

In [ ]:
# knowledge_base is simply everything combined. I can have defintions and steps without each other. Not harm.

# Before Merging Notes in see if there are Definitions which can be applied.

#display(notes_df)
notes_df = pd.read_csv(object_dict['csv_links']['python_object']['google_notes_csv']).fillna('')
definition_df = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])[['Process','Categorization','Word',"Definition"]].fillna('')

# Start with Items where Categorization is Process. These are Processes that Exist.

# Process refers to the Record itself.
# Categorization refers to the Type of Record that the individual item is. Which can Include Process, as it defines the charactersitics of the record

#display(definition_df)

# Before Merging Notes in see if there are Definitions which can be applied.

#display(notes_df)

notes_df1 = notes_df.merge(definition_df[['Process','Definition']].rename(columns={'Process':"Word",'Definition':'Definition_'}),on='Word',how='left').fillna("")
notes_df1['Definition'] = np.where((notes_df1['Categorization']=='Process Step')&(notes_df1['Definition']==""),notes_df1['Definition_'],notes_df1['Definition'])
notes_df1.drop('Definition_',axis=1,inplace=True)
notes_df1

In [ ]:
# Process >> Process Step >> __________

In [104]:
def generate_files_for_streamlit(
    definition_df=pd.DataFrame(),
    notes_df=pd.DataFrame(),
    generate_excel_files=True
):
    if len(definition_df)==0:
        definition_df = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])[['Process','Categorization','Word',"Definition"]].fillna('')

    if len(notes_df)==0:
        notes_df = pd.read_csv(object_dict['csv_links']['python_object']['google_notes_csv']).fillna('')

    # Before Merging Files. Update Notes to include Definitions from any item which is a Process from Definition.

    notes_df1 = notes_df.merge(definition_df[['Process','Definition']].rename(columns={'Process':"Word",'Definition':'Definition_'}),on='Word',how='left').fillna("")
    notes_df1['Definition'] = np.where((notes_df1['Categorization']=='Process Step')&(notes_df1['Definition']==""),notes_df1['Definition_'],notes_df1['Definition'])
    notes_df1.drop('Definition_',axis=1,inplace=True)

    # CREATE KNOWLEDGE File, which is simply everything combined Together
    knowledge_base_df = pd.concat([definition_df,notes_df1]).reset_index(drop=True)
    
    # Create 2 Distinct Files Processes. Not Processes
    processes = knowledge_base_df[knowledge_base_df['Categorization']=='Process'].reset_index(drop=True).reset_index().rename(columns={'index':'PROC_ORDER'})
    not_processes = knowledge_base_df[knowledge_base_df['Categorization']!='Process'].reset_index(drop=True).reset_index().rename(columns={'index':'NP_ORDER'})

    # Create a Supplemental File which are effectively Items which need to be merged into Processes to move from the Straw Man Process to a more fullsome 
    supplemental = not_processes.merge(final_df[['Word','Process']].drop_duplicates().rename(columns={'Process':'Process_','Word':"Process"}),on='Process',how='inner')
    supplemental['Word_'] = supplemental['Word'].copy()
    supplemental['Word'] = supplemental['Process'].copy()
    supplemental['Process'] = supplemental['Process_'].copy()
    supplemental.drop('Process_',axis=1,inplace=True)

    # Before Supplemental can be finalized, needs to merge into Final DF. to ORder BEFORE replacing Word with Word_
    final_df1 = pd.concat([final_df,supplemental])
    final_df1 = final_df1.merge(processes[['PROC_ORDER',"Process"]].rename(columns={'Process':"Word"}),on='Word',how='left')
    
    final_df1 = final_df1.sort_values(['Process','PROC_ORDER','CAT_ORDER','NP_ORDER'])
    final_df1['Categorization'] = np.where(final_df1['Word_'].notnull(),final_df1['Word'],final_df1['Categorization'])
    final_df1['Word'] = np.where(final_df1['Word_'].notnull(),final_df1['Word_'],final_df1['Word'])
    
    final_df1.drop('Word_',inplace=True,axis=1)

    # Create a DataFrame for the Highlevel Process, which is Processes and Process Steps.
    process_df = final_df1[final_df1['Categorization'].isin(['Process','Process Step'])].copy()

    if generate_excel_files:
        knowledge_base_df.to_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/knowledge_base.xlsx',index=False)
        process_df.to_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/defined_processes.xlsx',index=False)
        final_df1.to_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/consolidated_dataset.xlsx',index=False)
    
    return knowledge_base_df,process_df,final_df1

knowledge_base_df,process_df,consolidated_df = generate_files_for_streamlit(definition_df,notes_df)

In [105]:
knowledge_base_df

,Process,Categorization,Word,Definition
0,Goal Setting,Process,Definition,"Thought process utilized to establish a clear,..."
1,Problem Definition,Process,Definition,"A Clear, Concise and explicit definition of th..."
2,Data Collection,Process,Definition,"Data collection involves identifying, sourcing..."
3,Data Preparation,Process,Definition,Data preparation focuses on cleaning and struc...
4,Exploratory Data Analysis,Process,Definition,Foundational step in ensuring the success of a...
5,Feature Engineering,Process,Definition,Process of creating new input variables that b...
6,Feature Selection,Process,Definition,Process of identifying and retaining the most ...
7,Validation/ Model Selection,Process,Definition,The process of choosing the most appropriate a...
8,Training,Process,Definition,Process of fitting a machine learning model to...
9,Hyperparameter Tuning,Process,Definition,Optimizing the configuration settings that con...
10,Model Evaluation,Process,Definition,Process of measuring how well a trained model ...
11,Validation,Process,Definition,Validation is the process of assessing model p...
12,Model Summarization / Model Interpretability,Process,Definition,Process of explaining how a model makes predic...
13,Deployment,Process,Definition,Deployment is the process of integrating the t...
14,Monitoring,Process,Definition,Ongoing process of tracking model performance ...
15,"Bias, Fairness, and Ethics",Process,Definition,This step examines whether the model produces ...
16,Organization - Definition,Process,Definition,List used to manage the default order of items...
17,Machine Learning Lifecycle,Process,Definition,To Be Defined
18,Behavioural Economics,Concept,Anchoring Effect,A cognitive bias where people rely too heavily...
19,Behavioural Economics,Concept,Base Rate Fallacy,People ignore or undervalue general statistica...
20,Behavioural Economics,Concept,Bureaucratic Politics,Organization decision making paradigm in which...
21,Behavioural Economics,Concept,Biased Assimilation,Tendency to interpret information in a way tha...
22,Behavioural Economics,Concept,Blind spot bias,Cognitive bias where people are unaware of the...
23,Behavioural Economics,Concept,Confirmation Bias,Also known as Selective Perception. What peopl...
24,Behavioural Economics,Concept,Fast statistics,"Immoderate, intuitive, visceral, and powerful."
25,Behavioural Economics,Concept,Slow statistics,Thoughtful gathering of unbiased information.
26,Behavioural Economics,Concept,Truth-default theory,54% accurate identifying liar. We can identify...
27,Behavioural Economics,Concept,Illusion of Asymmetric Insights,The Belief that we know others better than the...
28,Behavioural Economics,Concept,Intertemporal choice,Refers to decisions that involve trade-offs b...
29,Behavioural Economics,Concept,Motivated reasoning,Cognitive phenomenon where people process info...
30,Behavioural Economics,Concept,Naive realism,Naïve realism is a concept from social psychol...
31,Behavioural Economics,Concept,Ostrich Effect,cognitive bias where people avoid information ...
32,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,..."
33,Machine Learning Lifecycle,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
34,Machine Learning Lifecycle,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
35,Machine Learning Lifecycle,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...
36,Machine Learning Lifecycle,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...
37,Machine Learning Lifecycle,Process Step,Feature Engineering,Process of creating new input variables that b...
38,Machine Learning Lifecycle,Process Step,Feature Selection,Process of identifying and retaining the most ...
39,Machine Learning Lifecycle,Process Step,Model Selection,
40,Machine Learning Lifecycle,Process Step,Training,Process of fitting a machine learning model to...
41,Machine Learning Lifecycle,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...
42,Machine Learning Lifecycle,Process Step,Model Evaluation,Process of measuring how well a trained model ...
43,Machine Learning Lifecycle,Process Step,Validation,Validation is the process of assessing model p...
44,Machine Learning Lifecycle,Process Step,Model Summarization / Model Interpretability,Process of explaining how a model makes predic...
45,Machine Learning Lifecycle,Process Step,Deployment,Deployment is the process of integrating the t...
46,Machine Learning Lifecycle,Process Step,Monitoring,Ongoing process of tracking model performance ...
47,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...
48,Goal Setting,Requirement,Specific,Describes what will be accomplished and what s...
49,Goal Setting,Requirement,Measurable,Includes a clear way to track progress or dete...
50,Goal Setting,Requirement,Achievable,"Realistic given available time, resources, ski..."
51,Goal Setting,Requirement,Relevant,"Aligns with broader priorities, such as team o..."
52,Goal Setting,Requirement,Time Bound,Includes a clear deadline or timeframe for com...

In [103]:
consolidated_df

,Process,Categorization,Word,Definition,NP_ORDER,CAT_ORDER,PROC_ORDER
0,"Bias, Fairness, and Ethics",Process,Definition,This step examines whether the model produces ...,NaN,0.0,NaN
1,Data Collection,Process,Definition,"Data collection involves identifying, sourcing...",NaN,0.0,NaN
2,Data Preparation,Process,Definition,Data preparation focuses on cleaning and struc...,NaN,0.0,NaN
3,Deployment,Process,Definition,Deployment is the process of integrating the t...,NaN,0.0,NaN
4,Exploratory Data Analysis,Process,Definition,Foundational step in ensuring the success of a...,NaN,0.0,NaN
5,Feature Engineering,Process,Definition,Process of creating new input variables that b...,NaN,0.0,NaN
6,Feature Selection,Process,Definition,Process of identifying and retaining the most ...,NaN,0.0,NaN
7,Goal Setting,Process,Definition,"Thought process utilized to establish a clear,...",NaN,0.0,NaN
8,Goal Setting,Requirement,Specific,Describes what will be accomplished and what s...,30.0,NaN,NaN
9,Goal Setting,Requirement,Measurable,Includes a clear way to track progress or dete...,31.0,NaN,NaN
10,Goal Setting,Requirement,Achievable,"Realistic given available time, resources, ski...",32.0,NaN,NaN
11,Goal Setting,Requirement,Relevant,"Aligns with broader priorities, such as team o...",33.0,NaN,NaN
12,Goal Setting,Requirement,Time Bound,Includes a clear deadline or timeframe for com...,34.0,NaN,NaN
13,Hyperparameter Tuning,Process,Definition,Optimizing the configuration settings that con...,NaN,0.0,NaN
15,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,...",14.0,1.0,0.0
39,Machine Learning Lifecycle,Goal Setting,Specific,Describes what will be accomplished and what s...,30.0,NaN,0.0
40,Machine Learning Lifecycle,Goal Setting,Measurable,Includes a clear way to track progress or dete...,31.0,NaN,0.0
41,Machine Learning Lifecycle,Goal Setting,Achievable,"Realistic given available time, resources, ski...",32.0,NaN,0.0
42,Machine Learning Lifecycle,Goal Setting,Relevant,"Aligns with broader priorities, such as team o...",33.0,NaN,0.0
43,Machine Learning Lifecycle,Goal Setting,Time Bound,Includes a clear deadline or timeframe for com...,34.0,NaN,0.0
16,Machine Learning Lifecycle,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th...",15.0,1.0,1.0
17,Machine Learning Lifecycle,Process Step,Data Collection,"Data collection involves identifying, sourcing...",16.0,1.0,2.0
18,Machine Learning Lifecycle,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...,17.0,1.0,3.0
19,Machine Learning Lifecycle,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...,18.0,1.0,4.0
20,Machine Learning Lifecycle,Process Step,Feature Engineering,Process of creating new input variables that b...,19.0,1.0,5.0
21,Machine Learning Lifecycle,Process Step,Feature Selection,Process of identifying and retaining the most ...,20.0,1.0,6.0
23,Machine Learning Lifecycle,Process Step,Training,Process of fitting a machine learning model to...,22.0,1.0,8.0
24,Machine Learning Lifecycle,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...,23.0,1.0,9.0
25,Machine Learning Lifecycle,Process Step,Model Evaluation,Process of measuring how well a trained model ...,24.0,1.0,10.0
26,Machine Learning Lifecycle,Process Step,Validation,Validation is the process of assessing model p...,25.0,1.0,11.0
28,Machine Learning Lifecycle,Process Step,Deployment,Deployment is the process of integrating the t...,27.0,1.0,13.0
29,Machine Learning Lifecycle,Process Step,Monitoring,Ongoing process of tracking model performance ...,28.0,1.0,14.0
30,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...,29.0,1.0,15.0
14,Machine Learning Lifecycle,Process,Definition,To Be Defined,NaN,0.0,NaN
22,Machine Learning Lifecycle,Process Step,Model Selection,,21.0,1.0,NaN
27,Machine Learning Lifecycle,Process Step,\tModel Summarization / Model Interpretability,,26.0,1.0,NaN
31,Model Evaluation,Process,Definition,Process of measuring how well a trained model ...,NaN,0.0,NaN
32,Model Summarization / Model Interpretability,Process,Definition,Process of explaining how a model makes predic...,NaN,0.0,NaN
33,Monitoring,Process,Definition,Ongoing process of tracking model performance ...,NaN,0.0,NaN
34,Organization - Definition,Process,Definition,List used to manage the default order of items...,NaN,0.0,NaN
35,Problem Definition,Process,Definition,"A Clear, Concise and explicit definition of th...",NaN,0.0,NaN
36,Training,Process,Definition,Process of fitting a machine learning model to...,NaN,0.0,NaN
37,Validation,Process,Definition,Validation is the process of assessing model p...,NaN,0.0,NaN
38,Validation/ Model Selection,Process,Definition,The process of choosing the most appropriate a...,NaN,0.0,NaN

In [89]:
# Need to Order.
processes = knowledge_base_df[knowledge_base_df['Categorization']=='Process'].reset_index(drop=True).reset_index().rename(columns={'index':'PROC_ORDER'})
not_processes = knowledge_base_df[knowledge_base_df['Categorization']!='Process'].reset_index(drop=True).reset_index().rename(columns={'index':'NP_ORDER'})

In [80]:
not_processes.head()

,NP_ORDER,Process,Categorization,Word,Definition
0,0,Behavioural Economics,Concept,Anchoring Effect,A cognitive bias where people rely too heavily...
1,1,Behavioural Economics,Concept,Base Rate Fallacy,People ignore or undervalue general statistica...
2,2,Behavioural Economics,Concept,Bureaucratic Politics,Organization decision making paradigm in which...
3,3,Behavioural Economics,Concept,Biased Assimilation,Tendency to interpret information in a way tha...
4,4,Behavioural Economics,Concept,Blind spot bias,Cognitive bias where people are unaware of the...

In [99]:
supplemental = not_processes.merge(final_df[['Word','Process']].drop_duplicates().rename(columns={'Process':'Process_','Word':"Process"}),on='Process',how='inner')
supplemental['Word_'] = supplemental['Word'].copy()
supplemental['Word'] = supplemental['Process'].copy()
supplemental['Process'] = supplemental['Process_'].copy()
supplemental.drop('Process_',axis=1,inplace=True)

# Before Supplemental can be finalized, needs to merge into Final DF. to ORder BEFORE replacing Word with Word_
final_df1 = pd.concat([final_df,supplemental])
final_df1 = final_df1.merge(processes[['PROC_ORDER',"Process"]].rename(columns={'Process':"Word"}),on='Word',how='left')

final_df1 = final_df1.sort_values(['Process','PROC_ORDER','CAT_ORDER','NP_ORDER'])
final_df1['Categorization'] = np.where(final_df1['Word_'].notnull(),final_df1['Word'],final_df1['Categorization'])
final_df1['Word'] = np.where(final_df1['Word_'].notnull(),final_df1['Word_'],final_df1['Word'])

final_df1.drop('Word_',inplace=True,axis=1)
final_df1

,Process,Categorization,Word,Definition,NP_ORDER,CAT_ORDER,PROC_ORDER
0,"Bias, Fairness, and Ethics",Process,Definition,This step examines whether the model produces ...,NaN,0.0,NaN
1,Data Collection,Process,Definition,"Data collection involves identifying, sourcing...",NaN,0.0,NaN
2,Data Preparation,Process,Definition,Data preparation focuses on cleaning and struc...,NaN,0.0,NaN
3,Deployment,Process,Definition,Deployment is the process of integrating the t...,NaN,0.0,NaN
4,Exploratory Data Analysis,Process,Definition,Foundational step in ensuring the success of a...,NaN,0.0,NaN
5,Feature Engineering,Process,Definition,Process of creating new input variables that b...,NaN,0.0,NaN
6,Feature Selection,Process,Definition,Process of identifying and retaining the most ...,NaN,0.0,NaN
7,Goal Setting,Process,Definition,"Thought process utilized to establish a clear,...",NaN,0.0,NaN
8,Goal Setting,Requirement,Specific,Describes what will be accomplished and what s...,30.0,NaN,NaN
9,Goal Setting,Requirement,Measurable,Includes a clear way to track progress or dete...,31.0,NaN,NaN
10,Goal Setting,Requirement,Achievable,"Realistic given available time, resources, ski...",32.0,NaN,NaN
11,Goal Setting,Requirement,Relevant,"Aligns with broader priorities, such as team o...",33.0,NaN,NaN
12,Goal Setting,Requirement,Time Bound,Includes a clear deadline or timeframe for com...,34.0,NaN,NaN
13,Hyperparameter Tuning,Process,Definition,Optimizing the configuration settings that con...,NaN,0.0,NaN
15,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,...",14.0,1.0,0.0
39,Machine Learning Lifecycle,Goal Setting,Specific,Describes what will be accomplished and what s...,30.0,NaN,0.0
40,Machine Learning Lifecycle,Goal Setting,Measurable,Includes a clear way to track progress or dete...,31.0,NaN,0.0
41,Machine Learning Lifecycle,Goal Setting,Achievable,"Realistic given available time, resources, ski...",32.0,NaN,0.0
42,Machine Learning Lifecycle,Goal Setting,Relevant,"Aligns with broader priorities, such as team o...",33.0,NaN,0.0
43,Machine Learning Lifecycle,Goal Setting,Time Bound,Includes a clear deadline or timeframe for com...,34.0,NaN,0.0
16,Machine Learning Lifecycle,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th...",15.0,1.0,1.0
17,Machine Learning Lifecycle,Process Step,Data Collection,"Data collection involves identifying, sourcing...",16.0,1.0,2.0
18,Machine Learning Lifecycle,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...,17.0,1.0,3.0
19,Machine Learning Lifecycle,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...,18.0,1.0,4.0
20,Machine Learning Lifecycle,Process Step,Feature Engineering,Process of creating new input variables that b...,19.0,1.0,5.0
21,Machine Learning Lifecycle,Process Step,Feature Selection,Process of identifying and retaining the most ...,20.0,1.0,6.0
23,Machine Learning Lifecycle,Process Step,Training,Process of fitting a machine learning model to...,22.0,1.0,8.0
24,Machine Learning Lifecycle,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...,23.0,1.0,9.0
25,Machine Learning Lifecycle,Process Step,Model Evaluation,Process of measuring how well a trained model ...,24.0,1.0,10.0
26,Machine Learning Lifecycle,Process Step,Validation,Validation is the process of assessing model p...,25.0,1.0,11.0
28,Machine Learning Lifecycle,Process Step,Deployment,Deployment is the process of integrating the t...,27.0,1.0,13.0
29,Machine Learning Lifecycle,Process Step,Monitoring,Ongoing process of tracking model performance ...,28.0,1.0,14.0
30,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...,29.0,1.0,15.0
14,Machine Learning Lifecycle,Process,Definition,To Be Defined,NaN,0.0,NaN
22,Machine Learning Lifecycle,Process Step,Model Selection,,21.0,1.0,NaN
27,Machine Learning Lifecycle,Process Step,\tModel Summarization / Model Interpretability,,26.0,1.0,NaN
31,Model Evaluation,Process,Definition,Process of measuring how well a trained model ...,NaN,0.0,NaN
32,Model Summarization / Model Interpretability,Process,Definition,Process of explaining how a model makes predic...,NaN,0.0,NaN
33,Monitoring,Process,Definition,Ongoing process of tracking model performance ...,NaN,0.0,NaN
34,Organization - Definition,Process,Definition,List used to manage the default order of items...,NaN,0.0,NaN
35,Problem Definition,Process,Definition,"A Clear, Concise and explicit definition of th...",NaN,0.0,NaN
36,Training,Process,Definition,Process of fitting a machine learning model to...,NaN,0.0,NaN
37,Validation,Process,Definition,Validation is the process of assessing model p...,NaN,0.0,NaN
38,Validation/ Model Selection,Process,Definition,The process of choosing the most appropriate a...,NaN,0.0,NaN

In [58]:
final_df[final_df['Word']=='Goal Setting']

,Process,Categorization,Word,Definition,NP_ORDER,CAT_ORDER
14,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,...",14.0,1.0

In [52]:
final_df = pd.concat([
    processes,
    not_processes[not_processes['Process'].isin(processes['Process'].unique())]
])

cat_order_dict = {'Process':0,'Process Step':1}
final_df['CAT_ORDER'] = final_df['Categorization'].map(cat_order_dict)
final_df = final_df.sort_values(['Process','CAT_ORDER','NP_ORDER'])
final_df

# Need to Merge Processes for Second Level Inclusion

,Process,Categorization,Word,Definition,NP_ORDER,CAT_ORDER
15,"Bias, Fairness, and Ethics",Process,Definition,This step examines whether the model produces ...,NaN,0.0
2,Data Collection,Process,Definition,"Data collection involves identifying, sourcing...",NaN,0.0
3,Data Preparation,Process,Definition,Data preparation focuses on cleaning and struc...,NaN,0.0
13,Deployment,Process,Definition,Deployment is the process of integrating the t...,NaN,0.0
4,Exploratory Data Analysis,Process,Definition,Foundational step in ensuring the success of a...,NaN,0.0
5,Feature Engineering,Process,Definition,Process of creating new input variables that b...,NaN,0.0
6,Feature Selection,Process,Definition,Process of identifying and retaining the most ...,NaN,0.0
0,Goal Setting,Process,Definition,"Thought process utilized to establish a clear,...",NaN,0.0
30,Goal Setting,Requirement,Specific,Describes what will be accomplished and what s...,30.0,NaN
31,Goal Setting,Requirement,Measurable,Includes a clear way to track progress or dete...,31.0,NaN
32,Goal Setting,Requirement,Achievable,"Realistic given available time, resources, ski...",32.0,NaN
33,Goal Setting,Requirement,Relevant,"Aligns with broader priorities, such as team o...",33.0,NaN
34,Goal Setting,Requirement,Time Bound,Includes a clear deadline or timeframe for com...,34.0,NaN
9,Hyperparameter Tuning,Process,Definition,Optimizing the configuration settings that con...,NaN,0.0
17,Machine Learning Lifecycle,Process,Definition,To Be Defined,NaN,0.0
14,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,...",14.0,1.0
15,Machine Learning Lifecycle,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th...",15.0,1.0
16,Machine Learning Lifecycle,Process Step,Data Collection,"Data collection involves identifying, sourcing...",16.0,1.0
17,Machine Learning Lifecycle,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...,17.0,1.0
18,Machine Learning Lifecycle,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...,18.0,1.0
19,Machine Learning Lifecycle,Process Step,Feature Engineering,Process of creating new input variables that b...,19.0,1.0
20,Machine Learning Lifecycle,Process Step,Feature Selection,Process of identifying and retaining the most ...,20.0,1.0
21,Machine Learning Lifecycle,Process Step,Model Selection,,21.0,1.0
22,Machine Learning Lifecycle,Process Step,Training,Process of fitting a machine learning model to...,22.0,1.0
23,Machine Learning Lifecycle,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...,23.0,1.0
24,Machine Learning Lifecycle,Process Step,Model Evaluation,Process of measuring how well a trained model ...,24.0,1.0
25,Machine Learning Lifecycle,Process Step,Validation,Validation is the process of assessing model p...,25.0,1.0
26,Machine Learning Lifecycle,Process Step,\tModel Summarization / Model Interpretability,,26.0,1.0
27,Machine Learning Lifecycle,Process Step,Deployment,Deployment is the process of integrating the t...,27.0,1.0
28,Machine Learning Lifecycle,Process Step,Monitoring,Ongoing process of tracking model performance ...,28.0,1.0
29,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...,29.0,1.0
10,Model Evaluation,Process,Definition,Process of measuring how well a trained model ...,NaN,0.0
12,Model Summarization / Model Interpretability,Process,Definition,Process of explaining how a model makes predic...,NaN,0.0
14,Monitoring,Process,Definition,Ongoing process of tracking model performance ...,NaN,0.0
16,Organization - Definition,Process,Definition,List used to manage the default order of items...,NaN,0.0
1,Problem Definition,Process,Definition,"A Clear, Concise and explicit definition of th...",NaN,0.0
8,Training,Process,Definition,Process of fitting a machine learning model to...,NaN,0.0
11,Validation,Process,Definition,Validation is the process of assessing model p...,NaN,0.0
7,Validation/ Model Selection,Process,Definition,The process of choosing the most appropriate a...,NaN,0.0

,Process,Categorization,Word,Definition
18,Behavioural Economics,Concept,Anchoring Effect,A cognitive bias where people rely too heavily...
19,Behavioural Economics,Concept,Base Rate Fallacy,People ignore or undervalue general statistica...
20,Behavioural Economics,Concept,Bureaucratic Politics,Organization decision making paradigm in which...
21,Behavioural Economics,Concept,Biased Assimilation,Tendency to interpret information in a way tha...
22,Behavioural Economics,Concept,Blind spot bias,Cognitive bias where people are unaware of the...
23,Behavioural Economics,Concept,Confirmation Bias,Also known as Selective Perception. What peopl...
24,Behavioural Economics,Concept,Fast statistics,"Immoderate, intuitive, visceral, and powerful."
25,Behavioural Economics,Concept,Slow statistics,Thoughtful gathering of unbiased information.
26,Behavioural Economics,Concept,Truth-default theory,54% accurate identifying liar. We can identify...
27,Behavioural Economics,Concept,Illusion of Asymmetric Insights,The Belief that we know others better than the...
28,Behavioural Economics,Concept,Intertemporal choice,Refers to decisions that involve trade-offs b...
29,Behavioural Economics,Concept,Motivated reasoning,Cognitive phenomenon where people process info...
30,Behavioural Economics,Concept,Naive realism,Naïve realism is a concept from social psychol...
31,Behavioural Economics,Concept,Ostrich Effect,cognitive bias where people avoid information ...
32,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,..."
33,Machine Learning Lifecycle,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
34,Machine Learning Lifecycle,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
35,Machine Learning Lifecycle,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...
36,Machine Learning Lifecycle,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...
37,Machine Learning Lifecycle,Process Step,Feature Engineering,Process of creating new input variables that b...
38,Machine Learning Lifecycle,Process Step,Feature Selection,Process of identifying and retaining the most ...
39,Machine Learning Lifecycle,Process Step,Model Selection,
40,Machine Learning Lifecycle,Process Step,Training,Process of fitting a machine learning model to...
41,Machine Learning Lifecycle,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...
42,Machine Learning Lifecycle,Process Step,Model Evaluation,Process of measuring how well a trained model ...
43,Machine Learning Lifecycle,Process Step,Validation,Validation is the process of assessing model p...
44,Machine Learning Lifecycle,Process Step,\tModel Summarization / Model Interpretability,
45,Machine Learning Lifecycle,Process Step,Deployment,Deployment is the process of integrating the t...
46,Machine Learning Lifecycle,Process Step,Monitoring,Ongoing process of tracking model performance ...
47,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...
48,Goal Setting,Requirement,Specific,Describes what will be accomplished and what s...
49,Goal Setting,Requirement,Measurable,Includes a clear way to track progress or dete...
50,Goal Setting,Requirement,Achievable,"Realistic given available time, resources, ski..."
51,Goal Setting,Requirement,Relevant,"Aligns with broader priorities, such as team o..."
52,Goal Setting,Requirement,Time Bound,Includes a clear deadline or timeframe for com...

In [25]:
# Consolidated Dataset

,Process,Categorization,Word,Definition
0,Machine Learning Lifecycle,Process Step,Goal Setting,"Thought process utilized to establish a clear,..."
1,Machine Learning Lifecycle,Process Step,Problem Definition,"A Clear, Concise and explicit definition of th..."
2,Machine Learning Lifecycle,Process Step,Data Collection,"Data collection involves identifying, sourcing..."
3,Machine Learning Lifecycle,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...
4,Machine Learning Lifecycle,Process Step,Exploratory Data Analysis,Foundational step in ensuring the success of a...
5,Machine Learning Lifecycle,Process Step,Feature Engineering,Process of creating new input variables that b...
6,Machine Learning Lifecycle,Process Step,Feature Selection,Process of identifying and retaining the most ...
7,Machine Learning Lifecycle,Process Step,Model Selection,
8,Machine Learning Lifecycle,Process Step,Training,Process of fitting a machine learning model to...
9,Machine Learning Lifecycle,Process Step,Hyperparameter Tuning,Optimizing the configuration settings that con...
10,Machine Learning Lifecycle,Process Step,Model Evaluation,Process of measuring how well a trained model ...
11,Machine Learning Lifecycle,Process Step,Validation,Validation is the process of assessing model p...
12,Machine Learning Lifecycle,Process Step,Model Interpretability,
13,Machine Learning Lifecycle,Process Step,Deployment,Deployment is the process of integrating the t...
14,Machine Learning Lifecycle,Process Step,Monitoring,Ongoing process of tracking model performance ...
15,Machine Learning Lifecycle,Process Step,"Bias, Fairness, and Ethics",This step examines whether the model produces ...

In [ ]:
# Select All Items where the Categorization is Process. Which means a Stand Alone Process.
# The processes might not be the Master Process, but they are a unique Stand Alone Process.