In [1]:
import pandas as pd
import numpy as np
import datetime

import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

from objects_automated import object_dict

In [7]:
df = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])

['Learning Paradigm', 'Algorithm Categorization', 'Method']

In [26]:
df[df['Process'].isin(base_df['Word'].tolist())]

,Process,Categorization,Word,Definition,Notes,Link,Image,Markdown Equation,Dataset Size,Learning Type,Algorithm Classification,Model Type
95,Information Retrieval,Definition,Inverse Document Frequency,IDF is a metric used in information retrieval ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,Information Retrieval,Definition,Term Frequency Saturation,The importance of a term in a document increas...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Information Retrieval,Definition,Semantic search,Search approach that focuses on understanding ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Information Retrieval,Definition,Reciprocal Rank Fusion,Method used to combine the results of multiple...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,Graph Algorithms,Method,Navigable Small World,Graph-based structure used in approximate near...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Information Retrieval,Definition,Reranking,Process of reordering retrieved search results...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,Clustering,Feature Selection,Variance Inflation Factor,\nVariance Inflation Factor a numerical measu...,NaN,NaN,NaN,\n## Variance Inflation Factor (VIF)\n\nThe Va...,NaN,NaN,NaN,NaN
121,Clustering,Model Selection,Inertia,"Quantitative measure used in clustering, parti...",NaN,NaN,NaN,\n$$\n\text{Inertia} = \sum_{i=1}^{n} \left\lV...,NaN,NaN,NaN,NaN
122,Clustering,Model Selection,Davies–Bouldin Index,Internal clustering evaluation metric that mea...,Davies–Bouldin: \n,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,Clustering,Model Selection,Calinski–Harabasz Index,"Also known as the Variance Ratio Criterion, is...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,Supervised Learning,Model Evaluation,Accuracy,Number of correctly classified examples divide...,NaN,NaN,NaN,$$ Accuracy = \frac{TP + TN}{TP + TN + FP + FN...,NaN,NaN,NaN,NaN
126,Supervised Learning,Model Evaluation,Confusion Matrix,Table used to evaluate the performance of a cl...,NaN,NaN,https://raw.githubusercontent.com/derek-dewald...,NaN,NaN,Assessment,Evaluation,NaN
127,Supervised Learning,Training,K Fold Cross Validation,Application of Cross Validation. Method for in...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,Supervised Learning,Training,Stratified Cross Validation,Increasing the Principle of Cross Validation a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,Method,Definition,Algorithm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
133,Method,Definition,Function,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,Method,Definition,Model,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
135,Method,Definition,OTHER METHODS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,Learning Paradigm,Definition,Supervised Learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,Learning Paradigm,Definition,Unsupervised Learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,Learning Paradigm,Definition,Semi-Supervised Learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,Learning Paradigm,Definition,Reinforcement Learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,Algorithm Categorization,Definition,Anomaly Detection,Algorithm which designed to identify observati...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,Algorithm Categorization,Definition,Classification,Algorithm which assign observations to one of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,Algorithm Categorization,Definition,Clustering,Algorithm which group observations into cluste...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,Algorithm Categorization,Definition,Regression,Algorithm which predict continuous numerical v...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,Algorithm Categorization,Definition,Ranking / Recommendation,Algorithm which order items or suggest relevan...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,Algorithm Categorization,Definition,Density Estimation,Approaches which involve modeling the underlyi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,Algorithm Categorization,Definition,Dimensionality Reduction,Algorithm which reduce the number of variables...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,Algorithm Categorization,Process Step,Feature Selection (AC),Methods that identify and retain a subset of e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,Algorithm Categorization,Definition,Feature Transformation,Methods which modify existing features into ne...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,Algorithm Categorization,Definition,Information Retrieval,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,Algorithm Categorization,Definition,Time Series Forecasting,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,Algorithm Categorization,Definition,Generative Models,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,Algorithm Categorization,Definition,Reinforcement Learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,Algorithm Categorization,Definition,Optimization,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,Algorithm Categorization,Definition,Graph Algorithms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,Algorithm Categorization,Definition,Prediction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,Representation Learning,Definition,Embedding model,"Machine learning model that converts text, ima...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,Algorithm Categorization,Definition,Representation Learning,Representation Learning is a class of machine ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,Representation Learning,Method,Contrastive Learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,Representation Learning,Method,Self-Supervised Learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,Representation Learning,Method,Autoencoding,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,Representation Learning,Method,Metric Learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162,Representation Learning,Method,Masked Language Modeling,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
163,Representation Learning,Algorithm,Word2Vec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,Representation Learning,Algorithm,BERT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,Representation Learning,Algorithm,Sentence-BERT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,Representation Learning,Algorithm,CLIP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,Representation Learning,Algorithm,SimCLR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,Representation Learning,Algorithm,Autoencoder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,Representation Learning,Algorithm,Variational Autoencoder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,Representation Learning,Algorithm,GraphSAGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,Representation Learning,Algorithm,Node2Vec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
base_df

,Process,Categorization,Word,Definition
129,ML Model Taxonomy,Definition,Learning Paradigm,How does the Model Learn?
130,ML Model Taxonomy,Definition,Algorithm Categorization,What problem is the model trying to solve
131,ML Model Taxonomy,Definition,Method,What Mathematical Method performs the task
132,Method,Definition,Algorithm,NaN
133,Method,Definition,Function,NaN
134,Method,Definition,Model,NaN
135,Method,Definition,OTHER METHODS,NaN
136,Learning Paradigm,Definition,Supervised Learning,NaN
137,Learning Paradigm,Definition,Unsupervised Learning,NaN
138,Learning Paradigm,Definition,Semi-Supervised Learning,NaN
139,Learning Paradigm,Definition,Reinforcement Learning,NaN
140,Algorithm Categorization,Definition,Anomaly Detection,Algorithm which designed to identify observati...
141,Algorithm Categorization,Definition,Classification,Algorithm which assign observations to one of ...
142,Algorithm Categorization,Definition,Clustering,Algorithm which group observations into cluste...
143,Algorithm Categorization,Definition,Regression,Algorithm which predict continuous numerical v...
144,Algorithm Categorization,Definition,Ranking / Recommendation,Algorithm which order items or suggest relevan...
145,Algorithm Categorization,Definition,Density Estimation,Approaches which involve modeling the underlyi...
146,Algorithm Categorization,Definition,Dimensionality Reduction,Algorithm which reduce the number of variables...
147,Algorithm Categorization,Process Step,Feature Selection (AC),Methods that identify and retain a subset of e...
148,Algorithm Categorization,Definition,Feature Transformation,Methods which modify existing features into ne...
149,Algorithm Categorization,Definition,Information Retrieval,NaN
150,Algorithm Categorization,Definition,Time Series Forecasting,NaN
151,Algorithm Categorization,Definition,Generative Models,NaN
152,Algorithm Categorization,Definition,Reinforcement Learning,NaN
153,Algorithm Categorization,Definition,Optimization,NaN
154,Algorithm Categorization,Definition,Graph Algorithms,NaN
155,Algorithm Categorization,Definition,Prediction,NaN
157,Algorithm Categorization,Definition,Representation Learning,Representation Learning is a class of machine ...

In [2]:


links = pd.read_csv(object_dict['csv_links']['python_object']['d_links'])
notes = pd.read_csv(object_dict['csv_links']['python_object']['google_notes_csv'])
definitions = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])
technical_notes = pd.read_csv(object_dict['csv_links']['python_object']['technical_notes'])

In [6]:
def search_column(
    df,
    word=None,
    column_name='Word'
):

    return df[df[column_name].fillna('').str.contains(word,case=False)]

search_column(definitions,'Wprd')

Empty DataFrame
Columns: [Process, Categorization, Word, Definition, Notes, Link, Image, Markdown Equation, Dataset Size, Learning Type, Algorithm Classification, Model Type]
Index: []

In [ ]:
def check_duplicates(df,column_name=None):
    if len(column_name)==0:
        for column in df.columns:

In [3]:
notes['Word'].value_counts()

Word
Requirement                                     33
Consideration                                    5
Feature Selection                                5
Goal Setting                                     3
Problem Definition                               2
Data Preparation                                 2
Model Summarization / Model Interpretability     2
Notes                                            2
What Meaning Does a KPI actually have?           1
Organizations                                    1
Think about the Medium                           1
Unintended Consequences KPIs                     1
Ratios or Observed Values                        1
Include Interactions                             1
How does Time Impact?                            1
Facts Vs Statistics                              1
Fact Believability                               1
Specific                                         1
Measurable                                       1
Achievable                                       1
Relevant                                         1
Time Bound                                       1
Desired State Metrics                            1
Current State Analysis                           1
Root Cause Assessment                            1
Historical Overview                              1
Baseline Metrics (Current State)                 1
Understand KPIs which are meaningful.            1
What Lens is Problem Defined?                    1
Stakeholder Investment?                          1
Really Understand Problem Statement              1
Challenges from Missing Data                     1
Who is the Steward                               1
Review Definitions                               1
Python Function                                  1
Documented                                       1
Communicated                                     1
Supported                                        1
Measured                                         1
Simple                                           1
Clear                                            1
Evident                                          1
Obvious                                          1
Accountability                                   1
Data Collection                                  1
Validation/ Model Selection                      1
Monitoring                                       1
Name: count, dtype: int64

In [45]:
definitions = pd.read_csv(object_dict['csv_links']['python_object']['google_definition_csv'])
definitions.head(2)

,Process,Categorization,Word,Definition,Notes,Link,Image,Markdown Equation,Dataset Size,Learning Type,Algorithm Classification,Model Type
0,Behavioural Economics,Concept,Anchoring Effect,A cognitive bias where people rely too heavily...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Behavioural Economics,Concept,Base Rate Fallacy,People ignore or undervalue general statistica...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
definitions['Word'].value_counts()

Word
Data Preparation             2
Feature Engineering          2
Anchoring Effect             1
Base Rate Fallacy            1
Bureaucratic Politics        1
                            ..
Graph Algorithms             1
Prediction                   1
Algorithm Parent Category    1
Algorithm Categorization     1
Method                       1
Name: count, Length: 111, dtype: int64

In [56]:
definitions.groupby('Word').size()

Word
Acyclic Graph                  1
Algorithm                      1
Algorithm Categorization       1
Algorithm Parent Category      1
Anchoring Effect               1
                              ..
Validation                     1
Validation/ Model Selection    1
Variance                       1
Volatility                     1
Weighted Bipartite Graph       1
Length: 111, dtype: int64

In [62]:
definitions.groupby('Word').cumcount()

0      0
1      0
2      0
3      0
4      0
      ..
108    0
109    0
110    0
111    0
112    0
Length: 113, dtype: int64

In [63]:
def check_duplication(df,column_name):
    ''''''
    df = df.copy()
    df['COUNT'] = df.groupby(column_name)[column_name].transform('size')

    return df[df['COUNT']>1]

check_duplication(definitions,'Word')

,Process,Categorization,Word,Definition,Notes,Link,Image,Markdown Equation,Dataset Size,Learning Type,Algorithm Classification,Model Type,COUNT
17,General Definition,Process Step,Data Preparation,Data preparation focuses on cleaning and struc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
19,General Definition,Process Step,Feature Engineering,Process of creating new input variables that b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
56,Dot Py String Classification,Definition,Data Preparation,"Function cleans, reshapes, filters, joins, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
58,Dot Py String Classification,Definition,Feature Engineering,"Function creates derived variables, metrics...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

In [44]:
definitions[definitions['Word'].str.contains('algo',case=False)]

,Process,Categorization,Word,Definition,Notes,Link,Image,Markdown Equation,Dataset Size,Learning Type,Algorithm Classification,Model Type
68,Mathematics,Theorem,Algorithm,An algorithm is a procedure that unfolds over ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
definitions[definitions['Word'].str.contains('Model',case=False)]

,Process,Categorization,Word,Definition,Notes,Link,Image,Markdown Equation,Dataset Size,Learning Type,Algorithm Classification,Model Type
21,General Definition,Process Step,Validation/ Model Selection,The process of choosing the most appropriate a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,General Definition,Process Step,Model Evaluation,Process of measuring how well a trained model ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,General Definition,Process Step,Model Summarization / Model Interpretability,Process of explaining how a model makes predic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Dot Py String Classification,Definition,Modeling & Analytics,"Function performs statistical analysis, ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,Algorithm Classification,Definition,Generative Models,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
definitions[definitions['Process']=='Algorithm Classification']['Word'].tolist()

['Anomaly Detection',
 'Classification',
 'Clustering',
 'Regression',
 'Ranking / Recommendation',
 'Density Estimation',
 'Dimensionality Reduction',
 'Feature Selection',
 'Feature Transformation',
 'Information Retrieval',
 'Time Series Forecasting',
 'Generative Models',
 'Reinforcement Learning',
 'Optimization',
 'Graphing',
 'Prediction']

In [22]:
algorithm_classification = {
    "Anomaly Detection": {
        "Parent Category": "Detection and Monitoring",
        "Algorithms": [
            "Isolation Forest",
            "One-Class SVM",
            "Local Outlier Factor",
            "Elliptic Envelope",
            "Autoencoder"
        ]
    },

    "Classification": {
        "Parent Category": "Supervised Learning",
        "Algorithms": [
            "Logistic Regression",
            "Decision Tree Classifier",
            "Random Forest Classifier",
            "Support Vector Machine",
            "Naive Bayes"
        ]
    },

    "Clustering": {
        "Parent Category": "Unsupervised Learning",
        "Algorithms": [
            "K-Means",
            "Hierarchical Clustering",
            "DBSCAN",
            "Gaussian Mixture Model",
            "Spectral Clustering"
        ]
    },

    "Regression": {
        "Parent Category": "Supervised Learning",
        "Algorithms": [
            "Linear Regression",
            "Ridge Regression",
            "Lasso Regression",
            "Random Forest Regressor",
            "Support Vector Regression"
        ]
    },

    "Ranking / Recommendation": {
        "Parent Category": "Ranking and Personalization",
        "Algorithms": [
            "Collaborative Filtering",
            "Matrix Factorization",
            "Learning to Rank",
            "Content-Based Filtering",
            "Neural Collaborative Filtering"
        ]
    },

    "Density Estimation": {
        "Parent Category": "Statistical and Probabilistic Modelling",
        "Algorithms": [
            "Kernel Density Estimation",
            "Gaussian Mixture Model",
            "Histogram Density Estimation",
            "k-Nearest Neighbour Density Estimation",
            "Normalizing Flow"
        ]
    },

    "Dimensionality Reduction": {
        "Parent Category": "Feature Engineering",
        "Algorithms": [
            "Principal Component Analysis",
            "Linear Discriminant Analysis",
            "t-SNE",
            "UMAP",
            "Autoencoder"
        ]
    },

    "Feature Selection": {
        "Parent Category": "Feature Engineering",
        "Algorithms": [
            "Recursive Feature Elimination",
            "Variance Threshold",
            "Mutual Information Selection",
            "Lasso Feature Selection",
            "Sequential Feature Selection"
        ]
    },

    "Feature Transformation": {
        "Parent Category": "Feature Engineering",
        "Algorithms": [
            "Standard Scaling",
            "Min-Max Scaling",
            "One-Hot Encoding",
            "Polynomial Feature Transformation",
            "Power Transformation"
        ]
    },

    "Information Retrieval": {
        "Parent Category": "Search and Retrieval",
        "Algorithms": [
            "BM25",
            "TF-IDF",
            "Vector Space Model",
            "Dense Passage Retrieval",
            "Hybrid Search"
        ]
    },

    "Time Series Forecasting": {
        "Parent Category": "Temporal Modelling",
        "Algorithms": [
            "ARIMA",
            "Exponential Smoothing",
            "Prophet",
            "Long Short-Term Memory Network",
            "Temporal Fusion Transformer"
        ]
    },

    "Generative Models": {
        "Parent Category": "Generative Learning",
        "Algorithms": [
            "Generative Adversarial Network",
            "Variational Autoencoder",
            "Diffusion Model",
            "Autoregressive Language Model",
            "Normalizing Flow"
        ]
    },

    "Reinforcement Learning": {
        "Parent Category": "Sequential Decision-Making",
        "Algorithms": [
            "Q-Learning",
            "Deep Q-Network",
            "SARSA",
            "Proximal Policy Optimization",
            "Actor-Critic"
        ]
    },

    "Optimization": {
        "Parent Category": "Optimization and Decision Science",
        "Algorithms": [
            "Gradient Descent",
            "Genetic Algorithm",
            "Simulated Annealing",
            "Particle Swarm Optimization",
            "Linear Programming"
        ]
    },

    "Graph Algorithms": {
        "Parent Category": "Graph and Network Analysis",
        "Algorithms": [
            "Dijkstra's Algorithm",
            "A* Search",
            "PageRank",
            "Louvain Community Detection",
            "Graph Neural Network"
        ]
    }
}

                                         Name
Graph Algorithms         Dijkstra's Algorithm
Graph Algorithms                    A* Search
Graph Algorithms                     PageRank
Graph Algorithms  Louvain Community Detection
Graph Algorithms         Graph Neural Network

In [39]:
pd.DataFrame(temp_,columns=['Name'],index=[key for x in range(len(temp_))])

                                    Name
Classification       Logistic Regression
Classification  Decision Tree Classifier
Classification  Random Forest Classifier
Classification    Support Vector Machine
Classification               Naive Bayes

In [41]:
final_df = pd.DataFrame()
for key in algorithm_classification.keys():
    temp_ = algorithm_classification[key]['Algorithms']
    final_df = pd.concat([
        final_df,
        pd.DataFrame(temp_,columns=['Name'],index=[key for x in range(len(temp_))])
    ])

final_df.to_excel('temp.xlsx')

In [66]:
term_classification = {
    "Semantic Search": {
        "Parent Category": "Information Retrieval",
        "Classification": "Retrieval Method",
        "Description": (
            "A search method that retrieves results based on meaning and "
            "context rather than exact keyword matches."
        )
    },

    "Embedding Model": {
        "Parent Category": "Machine Learning Model",
        "Classification": "Representation Model",
        "Description": (
            "A model that converts text, images, or other objects into "
            "numerical vector representations."
        )
    },

    "Contrastive Training": {
        "Parent Category": "Machine Learning Training",
        "Classification": "Training Technique",
        "Description": (
            "A training technique that teaches a model to place similar "
            "examples closer together and dissimilar examples farther apart."
        )
    },

    "Reciprocal Rank Fusion": {
        "Parent Category": "Information Retrieval",
        "Classification": "Ranking Fusion Algorithm",
        "Description": (
            "An algorithm that combines multiple ranked result lists using "
            "the reciprocal positions of the results."
        )
    },

    "Approximate Nearest Neighbours": {
        "Parent Category": "Vector Search",
        "Classification": "Search Method",
        "Description": (
            "A method for efficiently finding vectors that are approximately "
            "closest to a query vector."
        )
    },

    "Navigable Small World": {
        "Parent Category": "Vector Indexing",
        "Classification": "Graph-Based Indexing Algorithm",
        "Description": (
            "A graph-based method that connects nearby vectors to support "
            "efficient nearest-neighbour search."
        )
    },

    "Weaviate": {
        "Parent Category": "Software Technology",
        "Classification": "Vector Database Platform",
        "Description": (
            "A software platform for storing, indexing, searching, and "
            "managing vector embeddings and associated data."
        )
    },

    "Backpropagation": {
        "Parent Category": "Machine Learning Training",
        "Classification": "Optimization Algorithm",
        "Description": (
            "An algorithm that calculates gradients through a neural network "
            "so its parameters can be updated during training."
        )
    },

    "Chunking": {
        "Parent Category": "Data Processing",
        "Classification": "Text Processing Technique",
        "Description": (
            "A technique that divides a document or sequence into smaller "
            "segments for processing, indexing, or retrieval."
        )
    },

    "Bi-encoder": {
        "Parent Category": "Neural Network Model",
        "Classification": "Retrieval Model Architecture",
        "Description": (
            "A model architecture that independently encodes a query and a "
            "candidate into vectors for efficient similarity comparison."
        )
    },

    "Cross-encoder": {
        "Parent Category": "Neural Network Model",
        "Classification": "Ranking Model Architecture",
        "Description": (
            "A model architecture that jointly processes a query and candidate "
            "to produce a relevance score."
        )
    },

    "Contextualized Late Interaction over BERT": {
        "Parent Category": "Neural Information Retrieval",
        "Classification": "Retrieval Model Architecture",
        "Common Name": "ColBERT",
        "Description": (
            "A retrieval architecture that separately encodes queries and "
            "documents while retaining token-level representations for late "
            "interaction scoring."
        )
    },

    "Bidirectional Encoder Representations": {
        "Parent Category": "Language Model",
        "Classification": "Encoder Model Architecture",
        "Common Name": "BERT",
        "Description": (
            "A transformer-based language model architecture that learns "
            "context by processing text in both directions."
        )
    },

    "Reranking": {
        "Parent Category": "Information Retrieval",
        "Classification": "Ranking Technique",
        "Description": (
            "A technique that applies a more precise scoring method to reorder "
            "an initial set of retrieved results."
        )
    },

    "Named Entity Recognition": {
        "Parent Category": "Natural Language Processing",
        "Classification": "NLP Task",
        "Description": (
            "A task that identifies and categorizes entities such as people, "
            "organizations, locations, and dates in text."
        )
    },

    "Decoder": {
        "Parent Category": "Neural Network Architecture",
        "Classification": "Model Component",
        "Description": (
            "A model component that generates or reconstructs an output from "
            "encoded representations or previously generated outputs."
        )
    },

    "Encoder": {
        "Parent Category": "Neural Network Architecture",
        "Classification": "Model Component",
        "Description": (
            "A model component that transforms input data into an internal "
            "representation used by later model components."
        )
    }
}

,Parent Category,Classification,Description,Common Name
Semantic Search,Information Retrieval,Retrieval Method,A search method that retrieves results based o...,NaN
Embedding Model,Machine Learning Model,Representation Model,"A model that converts text, images, or other o...",NaN
Contrastive Training,Machine Learning Training,Training Technique,A training technique that teaches a model to p...,NaN
Reciprocal Rank Fusion,Information Retrieval,Ranking Fusion Algorithm,An algorithm that combines multiple ranked res...,NaN
Approximate Nearest Neighbours,Vector Search,Search Method,A method for efficiently finding vectors that ...,NaN
Navigable Small World,Vector Indexing,Graph-Based Indexing Algorithm,A graph-based method that connects nearby vect...,NaN
Weaviate,Software Technology,Vector Database Platform,"A software platform for storing, indexing, sea...",NaN
Backpropagation,Machine Learning Training,Optimization Algorithm,An algorithm that calculates gradients through...,NaN
Chunking,Data Processing,Text Processing Technique,A technique that divides a document or sequenc...,NaN
Bi-encoder,Neural Network Model,Retrieval Model Architecture,A model architecture that independently encode...,NaN
Cross-encoder,Neural Network Model,Ranking Model Architecture,A model architecture that jointly processes a ...,NaN
Contextualized Late Interaction over BERT,Neural Information Retrieval,Retrieval Model Architecture,A retrieval architecture that separately encod...,ColBERT
Bidirectional Encoder Representations,Language Model,Encoder Model Architecture,A transformer-based language model architectur...,BERT
Reranking,Information Retrieval,Ranking Technique,A technique that applies a more precise scorin...,NaN
Named Entity Recognition,Natural Language Processing,NLP Task,A task that identifies and categorizes entitie...,NaN
Decoder,Neural Network Architecture,Model Component,A model component that generates or reconstruc...,NaN
Encoder,Neural Network Architecture,Model Component,A model component that transforms input data i...,NaN

In [68]:
pd.DataFrame(term_classification).T.to_excel('test.xlsx')