In [ ]:
import pandas as pd
import numpy as np
import datetime

import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [ ]:
python_function_classification_dict = {
    'Data Acquisition':'Function retrieves or ingests data from external or internal sources.',
    'Data Preparation':'Function cleans, reshapes, filters, joins, or transforms data into usable form.',
    'Dataset Generation':'Function creates a new analytical or operational dataset.',
    'Feature Engineering':'Function creates derived variables, metrics, flags, or analytical features.',
    'Data Validation':'Function validates, reconciles, audits, or assesses data quality.',
    'Modeling & Analytics':'Function performs statistical analysis, machine learning, scoring, or analytical calculations.',
    'Reporting & Visualization':'Function prepares outputs for reporting, dashboards, exports, or visualization.',
    'Automation & Orchestration':'Function coordinates workflows, scheduling, cross-platform tasks, or operational processes.',
    'Other':'Definition falls outside of existing classification',
    'TBD': 'Has not yet been assessed or finalized'
}

python_function_sub_classification_dict = {
    "Extraction": "Pulls data from a source system, file, API, database, or external platform.",
    "Transformation": "Cleans, reshapes, joins, aggregates, or restructures data.",
    "Loading": "Writes, uploads, exports, or inserts data into a destination system.",
    "Aggregation": "Summarizes data across groups, time periods, entities, or categories.",
    "Filtering": "Creates a subset of data based on defined rules or criteria.",
    "Feature Engineering": "Creates analytical variables from existing data.",
    "Validation": "Checks data accuracy, completeness, consistency, or expected structure.",
    "Reconciliation": "Compares datasets or totals to identify differences or confirm alignment.",
    "Automation": "Automates a repeated manual process or workflow.",
    "Reporting": "Prepares data or outputs used in reports, dashboards, or monitoring.",
    "Bespoke Workflow": "Supports a specific, custom process that may not generalize broadly.",
    "Other": "Definition falls outside of existing classification",
    'TBD': 'Has not yet been assessed or finalized'
}

# Manually Maintained List of Python Function Files
function_table_dictionary = {
    'connections':'Functions Connecting to External Data Sources',
    'data_d_dicts':'Repository of Dictionaries which have been saved for Easy Use and Reference',
    'data_d_lists':'Repository of Lists which have been saved for Easy Use and Reference',
    'data_d_strings':'Repository of Strings which have been saved for Easy Use and Reference',
    'df_processing': 'Functions related to dataframe Transformations, including; Filtering, Slicing, Parsing, Transposing. Individual Column Level Transformations Primarily in FeatureEngineering',
    'dict_processing':'Functions related to Manipulating, Transforming and Altering Dictionaries',
    'input_functions_ignore':'Functions which are Created for Single Use, or I can not reconcile their purpose, but they are used as Input for previosuly created functions',
    'list_processing':'Functions related to Manipulating, Transforming and Altering Lists',
    'string_processing':'Functions related to Manipulating, Transforming and Altering Strings',
    'shared_folder':'Functions related to Management, Maintenance and Upkeep of Windows and Mac OS File Folders',
    'sql_':'Functions related to Processing of SQL',
    'utility_functions':"Functions which are in development, do not nicely fit into the existing schema, or otherwise need attention"
    }

# List of Historical Python Function Files, to be widdled down to Deletion as finalizing Work.
tbd = {
    'data_creation': "Functions related to the creation of Data, for testing, reference or validation",
    'df_eda':"Functions related to the Structured Exploration of Datasets, to understand and explain",
    'date_functions':'Functions related Manipulation, Change and process of datetime',
    'df_stats':"Functions utilizing Statistical Concepts, and Calculations",
    'feature_engineering':'Functions related to the creation of New Columns, excludes TEXT cleaning.',
    'ml_pipeline':"Functions related to Custom Build ML Pipelines, Approaches and Techniques",
    'validations':"Functions related to Validation of Dataframes, Data Sets and Comparisons. This differs from EDA, where it is only about understanding, not Comparison"
}

In [ ]:
def template_doc_string_print(text_=template_doc_string):
    '''

    Function to Return the Printed Value of the Doc String template_doc_string. Easier to Copy and Paste in this format opposed ot raw text.

    Parameters:
        text(str): String Value to be Printed, defaulted to template_doc_string
        
    Returns:
        string

    date_created:17-Dec-25
    date_last_modified: 17-Dec-25
    classification:TBD
    sub_classification:TBD
    usage:
        template_doc_string_print()
'''
    print(text_)


def gpt_question(list_,word_list=None):

    for word in list_:
        if not word_list:
            word_list = word
        else:
            word_list += f', {word}'
    text = f"""For the following words, can you please provide me for each word a definition which is 4-5 sentences highlighting the definition,\nits origin, its importance and application. If the word is a ML Model, can you also please define the following in point form,\ntype of ML learning, type of ML problem, size of data set it works best on, and anything else which might be appropriate.\nUnique Words: {word_list}
    """

    print(text)

In [ ]:
# Use Functions to Generate Lists which can be used in .py from

In [ ]:
# Have 2 Data Dictionaries 
# Work
# Personal - Need to Name the Two Clearly.

# Where will I store Information such as variables

## Review Daily List
## Priorize To Do List


## Document Pages:
- Knowledge Base
- Notes
- Definitions
- Frequency Summarization
- Technical Notes
- Words and Quotes
- Process Checklist - How to START AND FINISH WELL.
- Function List
- Function Parameters
- Folder Table of Content

# How I document things


# Machine Learning Code/ Projects
# Data Pipelines
# Career.
# Investing Guidelines
- Buy/ Sell Rules.
- EFT or Mutual Fund to comprising a well balanced and intelligent portfolio.


# Data Validation Process
# Data Exploration Process
# Synthetic Member Dataset
# Clustering ALog

# Data Dictionary
# Create LLM which can Answer Questions on my computer.
# Create LLM which is distributed to other computer.

In [ ]:

######################################
# Action Add DQ Item.
# Add Read Me, which Explanation of process and Definitions of all Categorizations.
# DQ Validation Component
# Question I need to ask Myself.
# Is it a Definition.
# Is it a Step in a Process
# Is it a Process
# Is it information Related to a Process.
# DQ Process 1: Need to Avoid Duplication of Word in ALL SHEETS.
# Definitions: Are Technical Definitions, descriptions and eloborate Notes describing a Term. 
# Notes: Merge in Definitions.
# Take Longer Listings and organize them, Models, BLUE, 
######################################
def set_manual_column_order(df,column_name,column_order):
    
    '''
    
    '''
    
    df[column_name] = pd.Categorical(df[column_name], categories=column_order, ordered=True)
    questions = {
    'Clustering':[
        'How can I mathematically Explain a Cluster.',
        'What is important.',
        'How can I determine what to drop, and when.',
        'How do I understand time components in Clusters.'
        ' The right way to think about “sweet spot”. The “sweet spot” is not: maximum variance explained, maximum number of features, maximum complexity It is: stable clusters, interpretable differences, consistent behavior across runs, sensitivity that matches your use case (short-term vs long-term behavior)',
        'Why ratios can be problematic in clustering.',
        'Ratios are: high signal, high risk. They:amplify noise, can dominate PCA, are hard to interpret. Rule: Try models with and without ratios Prefer simpler models unless ratios clearly add value. Ratios must earn their place.'   
    ]
}
How am I going to Store Notes?
How am I going to store Functions?
How am I going to establish Process.
How am I going to document Python Code and Functions.
!bash /Users/derekdewald/scripts/daily_shell_job.sh

# Consolidate Sheets in Streamlit.
# Have Read Me and Clear DOcumented process to remind self.
# Consolidate Notes such that it's also exportable and ordered.
## Need a process for Looking at a .py File and then ensuring I have a reference usage here so I can remember.
## Need to also Classify the models based on usage and Dates so I can see changes.
## Need to determine a plan to migrate to a single usage.
# Add Filter on Definition Summary
# COMBINE EVERYTHING IN NOTES. THEN CREATE A TAB WHICH IS PROCESS RELATED.
Categorization - Part of ML Project
When you feel that you have to make a deal, you’re going to make a bad deal.
Everything is a good idea, until it isn’t.
What did we learn from Facebook?
What did we learn from Enron.A
(base) derekdewald@Dereks-MacBook-Pro Github_Repo % du -sh .git
 48M	.git
Chroma db
https://author-ide.skills.network/render?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZF9pbnN0cnVjdGlvbnNfdXJsIjoiaHR0cHM6Ly9jZi1jb3Vyc2VzLWRhdGEuczMudXMuY2xvdWQtb2JqZWN0LXN0b3JhZ2UuYXBwZG9tYWluLmNsb3VkLzRWbnNfeURfS0xQZ2VIVm9BR2VFd2cvQ2hyb21hJTIwREIlMjBkZXRhaWxzJTIwZm9yJTIwUHl0aG9uLXYxLm1kP3Q9MTc0OTc0MTcyNCIsInRvb2xfdHlwZSI6Imluc3RydWN0aW9uYWwtbGFiIiwiYXRsYXNfZmlsZV9pZCI6MzMwNTg4LCJhZG1pbiI6ZmFsc2UsImlhdCI6MTc1NzY5NzcyNH0.vpErp00cCFjE0inxcYmDIR-wUuG0ZVRKwG8AOW7CoSs
https://author-ide.skills.network/render?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZF9pbnN0cnVjdGlvbnNfdXJsIjoiaHR0cHM6Ly9jZi1jb3Vyc2VzLWRhdGEuczMudXMuY2xvdWQtb2JqZWN0LXN0b3JhZ2UuYXBwZG9tYWluLmNsb3VkL0NQWFZOYUFDbjB1MkdOSzIxR1ZwWGcvdmVjdG9yZGIlMjBmb3IlMjByYWclMjBtb2R1bGUlMjAxJTIwY2hlYXRzaGVldC12MS5tZD90PTE3NTA1OTU2ODQiLCJ0b29sX3R5cGUiOiJpbnN0cnVjdGlvbmFsLWxhYiIsImF0bGFzX2ZpbGVfaWQiOjM0MDMxNSwiYWRtaW4iOmZhbHNlLCJpYXQiOjE3NTc2OTc3OTF9.9ZLBKgtrkpa8M1s-8BAcsNjVgsrYl3yQQfSijA-x8n4





Daily List
Migrate Away from @Shaw.ca

Loss - And all ways to measure
Optimization - and all ways to measure
Activation - And All Activation Functions.
How to select and use layers.
Metrics - Measure Model Performance
Cross Entropy. Binary and Categorical.
Ideas

    
Retrieval Augmentation Generation
LLM. No source. Outdated - RAG
Stops Haucluenation
If reliever is no good, causes issue
The RAG process comprises four steps: Text Embedding, Retrieval, Augmented Query Creation, and Model Generation.
Text Embedding converts user prompts and knowledge base documents into high-dimensional vectors using AI models such as BERT or GPT.

Build a Chat Bot, Web App

Virtual Environment
Poetry 
Notes
Design And Optimize Models
Automate Tasks 
Drive Innovation


ps aux | egrep "run_d2_job.sh|daily_shell_job.sh|daily_job.py" | grep -v egrep
ps aux
ps = process status
a = show processes for all users
u = show the owner of the process
x = include processes not attached to a terminal
| = “pipe” (send output to the next command)
egrep = search using a pattern
The quoted string means:
match anything containing
 run_d2_job.sh OR
 daily_shell_job.sh OR
 daily_job.py
| grep -v egrep
-v = invert match (exclude)
This removes the egrep command itself from the results (a common gotcha).
launchd, macOS’s scheduler
launchctl bootout gui/$(id -u)/com.derekdewald.daily_d2_job
launchctl = control launchd
bootout = unload / remove a job
gui/$(id -u) = your user’s launchd domain
$(id -u) expands to your user ID (e.g., 501)
com.derekdewald.daily_d2_job = the job’s label
launchctl list | grep com.derekdewald.daily_d2_job
What this is doing
launchctl list = show all loaded launchd jobs
launchctl bootstrap gui/$(id -u) /Users/derekdewald/Library/LaunchAgents/com.derekdewald.daily_d2_job.plist
gui/$(id -u)
This part defines which launchd domain the job belongs to.
id -u → outputs your numeric user ID (e.g. 501)
gui/501 → the GUI login session for that user
This means:
The job runs as you
It has access to:
Your user environment
Your home directory
GUI-session resources (keychains, etc.)
This is exactly what you want for:
User-level scripts
Jobs under ~/Library/LaunchAgents
Things that should not run as root
(d2) derekdewald@Dereks-MacBook-Pro DataDictionary % launchctl list | grep com.derekdewald.daily_d2_job
-	0	com.derekdewald.daily_d2_job
PID     LastExitStatus   Label
PID: -
- means the job is not currently running
This is totally normal for scheduled jobs (daily, interval-based, etc.)
If it were running, you’d see a PID number instead.
2️⃣ LastExitStatus: 0
0 = success
The last time this job ran, it exited cleanly
This is a very good sign
If you ever see:
non-zero (e.g. 1, 127) → script error
missing value → may not have run yet
3️⃣ Label: com.derekdewald.daily_d2_job
Confirms the job is:
Loaded
Registered correctly
Using the expected label
What this tells us overall ✅
✔ The LaunchAgent is loaded
 ✔ It has run at least once
 ✔ The last run succeeded
 ✔ It is idle right now, waiting for its next trigger
In other words: this is exactly what you want to see for a daily job.
Useful next checks (optional but powerful)
See full job details
launchctl print gui/$(id -u)/com.derekdewald.daily_d2_job
This will show:
Triggers
ProgramArguments
Environment
Last run timestamps
Manually run it now
If you want to test on demand:
launchctl kickstart gui/$(id -u)/com.derekdewald.daily_d2_job
Then re-check:
launchctl list | grep com.derekdewald.daily_d2_job
You may briefly see a PID appear.
Check logs (very important)
If your plist defines logs:
tail -n 50 ~/Library/Logs/com.derekdewald.daily_d2_job.out
tail -n 50 ~/Library/Logs/com.derekdewald.daily_d2_job.err
Or via unified logging:
log show --predicate 'process == "launchd"' --last 1h | grep daily_d2_job
TL;DR
That line:
-	0	com.derekdewald.daily_d2_job
means:
“Your job is loaded, healthy, not currently running, and last finished successfully.”
If you want, next we can:
sanity-check the plist
harden it (PATH, Python venv, logging)
add notifications on failure
or convert it into a reusable template for your other jobs
(d2) derekdewald@Dereks-MacBook-Pro DataDictionary % log show --predicate 'process == "launchd"' --last 1h | grep daily_d2_job
2026-01-26 12:01:54.029335-0800 0x5386e75  Default     0x0                  1      0    launchd: [gui/501/com.derekdewald.daily_d2_job:] launch already in progress
2026-01-26 12:11:08.961170-0800 0x5389913  Default     0x0                  1      0    launchd: [gui/501/com.derekdewald.daily_d2_job:] bootout initiated by: launchctl[48800]<-zsh[46861]<-login[46860]<-Terminal[52598]
2026-01-26 12:11:08.961199-0800 0x5389913  Default     0x0                  1      0    launchd: [gui/501/com.derekdewald.daily_d2_job:] service state: not running
2026-01-26 12:11:08.961237-0800 0x5389913  Default     0x0                  1      0    launchd: [gui/501/com.derekdewald.daily_d2_job:] canceling penalty-box spawn
2026-01-26 12:11:08.961247-0800 0x5389913  Default     0x0                  1      0    launchd: [gui/501/com.derekdewald.daily_d2_job:] internal event: SPAWNED, code = 89
2026-01-26 12:11:08.961251-0800 0x5389913  Default     0x0                  1      0    launchd: [gui/501 [100015]:] removing service: com.derekdewald.daily_d2_job
2026-01-26 12:11:08.961279-0800 0x5389913  Default     0x0                  1      0    launchd: [gui/501/com.derekdewald.daily_d2_job:] internal event: PETRIFIED, code = 0
(d2) derekdewald@Dereks-MacBook-Pro DataDictionary % 
Run a .sh file from zsh
derekdewald@Dereks-MacBook-Pro scripts % zsh daily_shell_job.sh 
What does ZSH stand for?
 ls ~/Library/LaunchAgents     
launchctl remove com.derekdewald.daily_d2_job 2>/dev/null
mv ~/Library/LaunchAgents/com.derekdewald.daily_shell_job.plist \
   ~/Library/LaunchAgents/com.derekdewald.daily_trigger_job.plist
nano ~/Library/LaunchAgents/com.derekdewald.daily_trigger_job.plist
ADD
launchctl bootstrap gui/$(id -u) ~/Library/LaunchAgents/com.derekdewald.daily_trigger_job.plist
Zero shot prompt - 1 example
Few shot prompting
COT Chain of Prompting
Self Consistency
Langchain - Prompt templates
LangChain Expression Language (or LCEL) - pipe operator 
DECODING_METHOD: This controls how the LLM selects its next token. The default is greedy decoding, where the model always picks the most probable next token. Alternatively, setting this to sampling lets you influence the randomness of the model’s choices (with temperature being a key factor to tweak). If you want more deterministic, predictable responses, use greedy. For more creative, varied outputs, go with sampling.
MAX_NEW_TOKENS: This sets the maximum number of tokens the LLM can generate in a response. Since both input and output tokens typically contribute to the cost of using the model, this parameter is important for managing usage. Here, we’re limiting the output to 100 new tokens
First of all, choosing an LLM model is deceptively complicated (it’s a whole topic in itself). While it’s tempting to focus on the specs alone—like token limits, training data, or number of parameters—these details will only take you so far. The real test comes when you evaluate how a model performs for your specific use cases.
Here are some important factors to consider when selecting a model:
Capabilities: Does the model meet your needs? For example, some models are multimodal, meaning they can handle images and text, while others are limited to text-only tasks.
Cost: How much does it cost to use the model, including both input and output tokens? Balancing cost with performance is key to ensuring long-term value.
Speed: How quickly does the model generate responses? In some use cases, speed is just as important as accuracy, especially in real-time applications.
Quality: How accurate and relevant are the model’s outputs for your tasks? You’ll need to run tests to evaluate if the responses meet your quality standards.
Other Considerations: Think about any specific vendors you may need to work with, licensing restrictions, or integrations with your existing systems.
Ultimately, you’ll want to experiment and run real-world tests to find the right fit for your needs. Specs can guide you, but hands-on testing against your own usecases is the only way to truly know if a model works for your unique scenarios.
lsof -i :7860
kill -9 <PID>
Granite 3.3 8B
Mixtral 8x7B model
https://www.ibm.com/products/watsonx-ai/foundation-models?utm_source=skills_network&utm_content=in_lab_content_link&utm_id=Lab-Gradio+interface+interact+with+LLM-v1_1745852533
https://author-ide.skills.network/render?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZF9pbnN0cnVjdGlvbnNfdXJsIjoiaHR0cHM6Ly9jZi1jb3Vyc2VzLWRhdGEuczMudXMuY2xvdWQtb2JqZWN0LXN0b3JhZ2UuYXBwZG9tYWluLmNsb3VkL1RVLXBVZlRFNU1jbTZ1aDVVS2VkY0EvU2ltaWxhcml0eSUyMFNlYXJjaC12MS5tZD90PTE3NTAxNDYzMTIiLCJ0b29sX3R5cGUiOiJpbnN0cnVjdGlvbmFsLWxhYiIsImF0bGFzX2ZpbGVfaWQiOjMyNDgwMSwiYWRtaW4iOmZhbHNlLCJpYXQiOjE3NTc2OTc2NTZ9.iuoj9D9eTel7I1gzDNT4JyWjg2nQWdA3_zGZ3B5cwEo

Greedy decoding
What is a transformer
Attention
Temperature
Top k top p, what else. Can I do to tune a llm
System/user/admin
Types of prompt
Residual.
MSE
RMSE
Data - Function - Prediction.
Exam focused on why and when you use Services.
Lake Formation - Centre Block, ETL, Security, Access, Etc.
FGAC - Fine Grated Access Control.
S3 - Lifecycle Configuration
Managing Storage Lifecycle help to keep costs down.
Standard Storage Vs Glacier Storage
Expiration Actions.
Elastic File System
Lustre
Don’t count input Layer in NN, it is layer 0
HCLLP
Indifference will keep in and ruin your life.
Unconfessed Sin follows you, and effects more than you.


Remember
numerous based on legacy ISCU processes
Processes not documented
Processes not tested or controlled
Numero not documented
Requirements unclear, undefined.
DQ VALIDATION EXPLANATION. 
how to test indivisible Data point
How to test Peridoc change.
Documenting Lessons Learnt. - In Both Workframe and Job Interviewing
AWS
Integration

Goal | Measure of Success | Benefits | Challenges | Activities - Align to work log
RASCI = Understand how to reference discussion , integrate (Practically, Friendly, Realisitically) 
My Focus| Responsibility| Motivation | Clarification Required | 
How can we effectively seek clarification on projects where ambiguity exists, how to escalate in instances where appropriate consideration has not been given or resources not ascribed or allocated. Example Questions who made this decision. Where is the supporting documentation, where decisions are made without appropriate inclusion, what are the repercussions and as a organization how do we prevent this from recoccuring..
Communication
Context
What is my goal
Who is my audience
What is this information Important
Effectiveness
What would be considered effective
How would I know if this message is understood
How will I measure this
Medium
Why I am using this medium
Review Strategy
Is it necessary
Is my tone appropriate
Is the message clear.
Is there an ask or expectation
Am I as brief as possible
What is the takeaway
D Priorities
Data Set Creation
Data Set Documentation.
Data Set Validation
ML Project 1, 2, 3






    
Cluster.
Decile
Attrition
Product Definition.
Organization Performance Dashboard’


Variable Creation
Internal Member
Notes
Documenting Use Cases
Clarifying Expectations
Bringing Visibility & Consistency 
Linear
closed form
GD
Equation
Vector form.
RMSE
MSE
Learning rate
Global - local
2d needle in hay stack opposed to 300d
Slope
Partial derivative
Speed of decent
Epochs
Tolerance
Batch
Mini batch
Stochastic
Polynomial regression
28,888
While GFS provided a fault-tolerant and distributed filesystem across many commodity hardware servers in a cluster farm, Bigtable offered scalable storage of structured data across GFS.
the MapReduce framework on HDFS had a few shortcomings.
First, it was hard to manage and administer, with cumbersome operational complexity. Second, its general batch-processing MapReduce API was verbose and required a lot of boilerplate setup code, with brittle fault tolerance
Third, with large batches of data jobs with many pairs of MR tasks, each pair’s intermediate computed result is written to the local disk for the subsequent stage of its operation (see Figure 1-1). This repeated performance of disk I/O took its toll: large MR jobs could run for hours on end, or even days.
Apache Spark is a unified engine designed for large-scale distributed data processing, on premises in data centers or in the cloud.
And finally, even though Hadoop MR was conducive to large-scale jobs for general batch processing, it fell short for combining other workloads such as machine learning, streaming, or interactive SQL-like queries
Speed
Ease of use
Modularity
Extensibility
Spark focuses on its fast, parallel computation engine rather than on storage. Unlike Apache Hadoop, which included both storage and compute, Spark decouples the two b
Explain How I can add Additional Features into a Model, like Exponential to Explain. IE Tensor Flow Playground.
AI Agents
making plans and taking actions to achieve goals. It combines a Language Model's (LM) ability to reason with the practical ability to act, allowing it to handle complex, multi-step tasks that a model alone cannot. 
Core Anatomy: Deconstructing an agent into its three essential components: the
reasoning Model, actionable Tools, and the governing Orchestration Layer.
• A Taxonomy of Capabilities: Classifying agents from simple, connected problem-solvers
to complex, collaborative multi-agent systems.
• Architectural Design: Diving into the practical design considerations for each
component, from model selection to tool implementation.
• Building for Production: Establishing the Agent Ops discipline needed to evaluate,
debug, secure, and scale agentic systems from a single instance to a fleet with
enterprise governance.
1. Get the Mission: The process is initiated by a specific, high-level goal. This mission is
provided by a user (e.g., "Organize my team's travel for the upcoming conference") or an
automated trigger (e.g., "A new high-priority customer ticket has arrived").
2. Scan the Scene: The agent perceives its environment to gather context. This involves
the orchestration layer accessing its available resources: "What does the user's request
say?", "What information is in my term memory? Did I already try to do this task? Did the
user give me guidance last week?", "What can I access from my tools, like calendars,
databases, or APIs?"
3. Think It Through: This is the agent's core "think" loop, driven by the reasoning model. The
agent analyzes the Mission (Step 1) against the Scene (Step 2) and devises a plan. This
isn't a single thought, but often a chain of reasoning: "To book travel, I first need to know
who is on the team. I will use the get_team_roster tool. Then I will need to check their
availability via the calendar_api."
4. Take Action: The orchestration layer executes the first concrete step of the plan.
It selects and invokes the appropriate tool—calling an API, running a code function,
or querying a database. This is the agent acting on the world beyond its own
internal reasoning.
5. Observe and Iterate: The agent observes the outcome of its action. The get_
team_roster tool returns a list of five names. This new information is added to the
agent's context or "memory." The loop then repeats, returning to Step 3: "Now that I
have the roster, my next step
Start with Trying to Be Perfect, then work towards generalization.
- Training Doesn’t start (Loss doesn’t decrease)
- As you can literally train any data, there is something wrong if this occurs. Data Structure, Optimizer, Initial Weight, Learning Rate, Batch Size.
- Model Doesnt Beat Baseline
- Model Structure
- Can’t Severly Overfit despite trying.
- Increase Model Complexity and Size.
- If model is too complex, it can learn things that don’t exist, 
- L1 L2 Weight decay
Read Me? ?
WHAT IS THE PROCESS That this should be representing.
ML Model - Different Type of Model, Explaining what they are and when they are useful
tt: Baxga7-zopzut-jyzmod
Hypothesis tests:
 “Is branch A statistically different from the overall population?”
Effect sizes:
 “How large is the difference, not just whether it exists?”
Outlier detection:
 “Which branches behave unusually compared to peers?”
Variance decomposition:
 “How much variance is explained by branch vs entity vs city?”
Clustering:
 “Which branches behave similarly across metrics?”
Change detection over time:
 “Which groups materially shifted month-over-month?”
How to effectively Run a Campaign. 
Member Engagement Monitoring
Member Targets
Total Calls
Members Contacted
Members Engaged
Product Sold
Contacted Group Performance
Engaged Group Performance
Non Engaged Group Performance
Reference Group 0
Reference Group 1
Telling a Story.
Thank Everyone
Don’t Assume Subject is Dull
Don’t Criticize until you hear the person out
Don’t let prejudices Close your mind
Don’t waste the advantage that thought has over speech
Speak, LORD, for Your servant is listening” (1 Samuel 3:9).
Most of us were born hearing well, but all of us must learn to listen well.
if a speaker utters 120 words a minute, the audience thinks at about 500 words a minute. 
Precision, recall, cm, accuracy, f1 , harmonic mean, auc
NN
RELU
Dense Connection
Structure
RNN, CNN, 
Sequence Data.

In [ ]:
def log_transformation(df,column_name,new_column_name=None,include_negative=False):
    
    '''
    
    '''
    if not new_column_name:
        new_column_name = f"{column_name}_LOG"
    
    if include_negative:
        col = np.abs(df[column_name])
        sign = np.sign(df[column_name])
        df.loc[:, new_column_name] = np.log1p(col)*sign
    
    else:
        col = df[column_name].clip(lower=0)
        df.loc[:, new_column_name] = np.log1p(col)     


def clip_distriubution(df,column_name,new_column_name=None,head=None,tail=None):
    if not new_column_name:
        new_column_name = f"{column_name}_CLIPPED"

    col = df[column_name]

    if head:
        col = col.clip(upper=head)
    if tail:
        col = col.clip(upper=tail)

    df[new_column_name] = col

In [1]:
import pandas as pd
import numpy as np
import datetime

import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

In [3]:
from dict_processing import generate_parameter_table

df = generate_parameter_table()
df

,COLUMN_NAME,SOURCE,DEFINITION,IS_PARAMETER
0,Data Acquisition,python_function_classification,Function retrieves or ingests data from extern...,1
1,Data Preparation,python_function_classification,"Function cleans, reshapes, filters, joins, or ...",1
2,Dataset Generation,python_function_classification,Function creates a new analytical or operation...,1
3,Feature Engineering,python_function_classification,"Function creates derived variables, metrics, f...",1
4,Data Validation,python_function_classification,"Function validates, reconciles, audits, or ass...",1
5,Modeling & Analytics,python_function_classification,"Function performs statistical analysis, machin...",1
6,Reporting & Visualization,python_function_classification,"Function prepares outputs for reporting, dashb...",1
7,Automation & Orchestration,python_function_classification,"Function coordinates workflows, scheduling, cr...",1
8,Other,python_function_classification,Definition falls outside of existing classific...,1
9,TBD,python_function_classification,Has not yet been assessed or finalized,1
0,Extraction,python_function_sub_classification,"Pulls data from a source system, file, API, da...",1
1,Transformation,python_function_sub_classification,"Cleans, reshapes, joins, aggregates, or restru...",1
2,Loading,python_function_sub_classification,"Writes, uploads, exports, or inserts data into...",1
3,Aggregation,python_function_sub_classification,"Summarizes data across groups, time periods, e...",1
4,Filtering,python_function_sub_classification,Creates a subset of data based on defined rule...,1
5,Feature Engineering,python_function_sub_classification,Creates analytical variables from existing data.,1
6,Validation,python_function_sub_classification,"Checks data accuracy, completeness, consistenc...",1
7,Reconciliation,python_function_sub_classification,Compares datasets or totals to identify differ...,1
8,Automation,python_function_sub_classification,Automates a repeated manual process or workflow.,1
9,Reporting,python_function_sub_classification,"Prepares data or outputs used in reports, dash...",1
10,Bespoke Workflow,python_function_sub_classification,"Supports a specific, custom process that may n...",1
11,Other,python_function_sub_classification,Definition falls outside of existing classific...,1
12,TBD,python_function_sub_classification,Has not yet been assessed or finalized,1

{'Data Quality', 'Dataset', 'ETL', 'Feature Creation'}

In [ ]:
def log_transformation(df,column_name,new_column_name=None,include_negative=False):
    
    '''



    
    '''
    if not new_column_name:
        new_column_name = f"{column_name}_LOG"
    
    if include_negative:
        col = np.abs(df[column_name])
        sign = np.sign(df[column_name])
        df.loc[:, new_column_name] = np.log1p(col)*sign
    
    else:
        col = df[column_name].clip(lower=0)
        df.loc[:, new_column_name] = np.log1p(col)     


def clip_distriubution(df,column_name,new_column_name=None,head=None,tail=None):
    if not new_column_name:
        new_column_name = f"{column_name}_CLIPPED"

    col = df[column_name]

    if head:
        col = col.clip(upper=head)
    if tail:
        col = col.clip(upper=tail)

    df[new_column_name] = col

In [43]:



generate_parameter_table(parameter_inclusion)

,COLUMN_NAME,SOURCE,DEFINITION,IS_PARAMETER
0,Data Acquisition,python_function_classification,Function retrieves or ingests data from extern...,1
1,Data Preparation,python_function_classification,"Function cleans, reshapes, filters, joins, or ...",1
2,Dataset Generation,python_function_classification,Function creates a new analytical or operation...,1
3,Feature Engineering,python_function_classification,"Function creates derived variables, metrics, f...",1
4,Data Validation,python_function_classification,"Function validates, reconciles, audits, or ass...",1
5,Modeling & Analytics,python_function_classification,"Function performs statistical analysis, machin...",1
6,Reporting & Visualization,python_function_classification,"Function prepares outputs for reporting, dashb...",1
7,Automation & Orchestration,python_function_classification,"Function coordinates workflows, scheduling, cr...",1
8,Other,python_function_classification,Definition falls outside of existing classific...,1
9,TBD,python_function_classification,Has not yet been assessed or finalized,1
0,Extraction,python_function_sub_classification,"Pulls data from a source system, file, API, da...",1
1,Transformation,python_function_sub_classification,"Cleans, reshapes, joins, aggregates, or restru...",1
2,Loading,python_function_sub_classification,"Writes, uploads, exports, or inserts data into...",1
3,Aggregation,python_function_sub_classification,"Summarizes data across groups, time periods, e...",1
4,Filtering,python_function_sub_classification,Creates a subset of data based on defined rule...,1
5,Feature Engineering,python_function_sub_classification,Creates analytical variables from existing data.,1
6,Validation,python_function_sub_classification,"Checks data accuracy, completeness, consistenc...",1
7,Reconciliation,python_function_sub_classification,Compares datasets or totals to identify differ...,1
8,Automation,python_function_sub_classification,Automates a repeated manual process or workflow.,1
9,Reporting,python_function_sub_classification,"Prepares data or outputs used in reports, dash...",1
10,Bespoke Workflow,python_function_sub_classification,"Supports a specific, custom process that may n...",1
11,Other,python_function_sub_classification,Definition falls outside of existing classific...,1
12,TBD,python_function_sub_classification,Has not yet been assessed or finalized,1

NameError: name 'python_function_classification_dict' is not defined

In [ ]:
# Current Status
# Working on Consolidated D Notes.
# Using ML Project and Clustering as Example. 
# Utilizing the Structure of ML Project where relevant for Categorization. 
# Process Step/ Consideration/ General KNowledge. 

# DEfinitons - where the should be everything else. 
# How to move BLUE intellegently.

Lesson Learned - Something discovered from experience
Advice
Requirement
Consideration - 

/ Best Practice	General recommendation	“Always check class imbalance before training”
Consideration	Something to think about before acting	“Does this variable represent behavior or outcome?”
Error / Pitfall	Mistake or common failure	“Target leakage from post-event variables”
Decision Rule	A conditional rule or heuristic	“If dataset <10k rows, avoid deep learning”
Trade-off	When two options both have cost/benefit	“Interpretability vs predictive power”
Diagnostic Signal

Consider -
Toll - 
Avoid - 
Decision - 


Check - 
Do - 
Avoid - 
Decide -

In [ ]:
import holidays

class TimeSeriesForecastPipeline:
    def __init__(
        self,
        date_col: str,
        target_col: str,
        country_holidays: str = "CA",
        province: str | None = None,
        lags: list[int] = None,
        rolling_windows: list[int] = None,
    ):
        self.date_col = date_col
        self.target_col = target_col
        self.country_holidays = country_holidays
        self.province = province
        self.lags = lags if lags is not None else [1, 7, 14, 21, 28]
        self.rolling_windows = rolling_windows if rolling_windows is not None else [7, 14, 28]

        s

        self.feature_cols = None
        self.train_df_ = None



    def _build_features(self, df: pd.DataFrame) -> pd.DataFrame:
        df = self._prepare_base_df(df)
        df = self._add_calendar_features(df)
        df = self._add_lag_features(df)
        return df

    def fit(self, df: pd.DataFrame, train_end_date: str | None = None):
        df_feat = self._build_features(df)

        # drop rows where target is missing
        df_feat = df_feat[~df_feat[self.target_col].isna()].copy()

        # feature columns
        self.feature_cols = [
            c for c in df_feat.columns
            if c not in [self.date_col, self.target_col]
        ]

        # remove rows with NA features from lagging/rolling
        model_df = df_feat.dropna(subset=self.feature_cols).copy()

        if train_end_date is not None:
            train_end_date = pd.to_datetime(train_end_date)
            model_df = model_df[model_df[self.date_col] <= train_end_date].copy()

        X_train = model_df[self.feature_cols]
        y_train = model_df[self.target_col]

        self.model.fit(X_train, y_train)
        self.train_df_ = df.copy()

        return self

    def predict_historical(self, df: pd.DataFrame, test_start_date: str):
        df_feat = self._build_features(df)
        df_feat = df_feat[~df_feat[self.target_col].isna()].copy()

        test_start_date = pd.to_datetime(test_start_date)

        usable_df = df_feat.dropna(subset=self.feature_cols).copy()
        test_df = usable_df[usable_df[self.date_col] >= test_start_date].copy()

        X_test = test_df[self.feature_cols]
        test_df["prediction"] = self.model.predict(X_test)

        mae = mean_absolute_error(test_df[self.target_col], test_df["prediction"])
        rmse = np.sqrt(mean_squared_error(test_df[self.target_col], test_df["prediction"]))

        return test_df[[self.date_col, self.target_col, "prediction"]], {
            "MAE": mae,
            "RMSE": rmse
        }

    def predict_next_day(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Predict the next day after the latest available date.
        """
        df = self._prepare_base_df(df).copy()
        last_date = df[self.date_col].max()
        next_date = last_date + pd.Timedelta(days=1)

        # append empty next day row
        next_row = pd.DataFrame({
            self.date_col: [next_date],
            self.target_col: [np.nan]
        })
        temp_df = pd.concat([df, next_row], ignore_index=True)

        # build features
        feat_df = self._build_features(temp_df)

        pred_row = feat_df[feat_df[self.date_col] == next_date].copy()

        X_pred = pred_row[self.feature_cols]
        pred_value = self.model.predict(X_pred)[0]

        return pd.DataFrame({
            self.date_col: [next_date],
            "prediction": [pred_value]
        })


# Day of Week
# Day of Month
# Month
# Season
# Weekday
# Weekend
# holiday

# Box Plot by Each of the Variables.

~np.isclose(
        d['BRANCH_7D_CHANGE'],
        d['MBR_7D_CHANGE'],
        equal_nan=True
    )

def binary_complex_equivlance(df, col, col1, new_column_name):
    try:
        # Try numeric comparison
        df[new_column_name] = np.where(
            (df[col].isna() & df[col1].isna()) |
            ((df[col].fillna(0) == 0) & df[col1].isna()) |
            ((df[col1].fillna(0) == 0) & df[col].isna()) |
            (df[col].fillna(0) == df[col1].fillna(0)),
            1, 0
        )
    except Exception:
        # Fallback to string comparison
        df[new_column_name] = np.where(
            (df[col].isna() & df[col1].isna()) |
            ((df[col].fillna('') == '') & df[col1].isna()) |
            ((df[col1].fillna('') == '') & df[col].isna()) |
            (df[col].fillna('').astype(str).str.strip().str.lower() ==
             df[col1].fillna('').astype(str).str.strip().str.lower()),
            1, 0
        )
    return df


def df_column_comparison_binary(
    df,
    df1,
    primary_key_list,
    column_list=[]):

    d = df.merge(df1,on=primary_key_list,how='outer',suffixes=("","_"))

    if len(column_list)==0:
        column_list = d.columns
    
    for col in column_list:
        if (col in primary_key_list)| (col[-1]=='_') :
            pass
        else:
            try:
                df = binary_complex_equivlance(d,col,f"{col}_",f"{col}_FLAG")
            except:
                print(f'Column:{col} is Missing from One of the DF')


def column_comparison_df(
    df,
    primary_key,
    indicator='_'
):
    for col in df.columns:      
        if (col in primary_key)|(col[-1:]=='_')|(col=='_merge')|(col.find('_FLAG')!=-1):
            #print(col,'Passed')
            pass
        else:
            #print(col,'Not Passed')
            column_comparison(df,col,primary_key=primary_key)
    df['TOTAL_FLAGS']= r[[x for x in r.columns if x.find('_FLAG')!=-1]].sum(axis=1)
    


def search_missing_date(date_list,freq='d'):
    all_dates = pd.date_range(
        start=date_list.min(),
        end=date_list.max(),
        freq=freq)

    return all_dates.difference(date_list)

df['MONTH_WON'] = pd.NaT
mask = df['statuscode'] == 3
df.loc[mask, 'MONTH_WON'] = (
    df.loc[mask,'actualclosedate']
      .dt.to_period('M')
      .dt.to_timestamp('M')
)

with pd.ExcelWriter(filename, engine="xlsxwriter") as writer:
    # ---- Write the dataframes ----
    df.to_excel(writer, index=False, sheet_name="ALL_ACCOUNTS_OPENED")
    df1.to_excel(writer, index=False, sheet_name="SAMPLE_NEW_RETAIL_MEMBERSHIPS")

    workbook = writer.book

    # ---- Define formats ----
    acct_format = workbook.add_format({'num_format': '0'})
    date_format = workbook.add_format({'num_format': 'yyyy-mm-dd'})

    wrap_center = workbook.add_format({
        'text_wrap': True,
        'align': 'center',
        'valign': 'vcenter'
    })

    # ============================================================
    # ✅ Format Sheet 1
    # ============================================================
    ws1 = writer.sheets["ALL_ACCOUNTS_OPENED"]

    # --- Auto-size + wrap/center all columns ---
    for idx, col in enumerate(df.columns):
        max_len = min(
            80,
            max(df[col].astype(str).map(len).max(), len(col)) + 2
        )
        ws1.set_column(idx, idx, max_len, wrap_center)

    # --- Override ACCT and DATE formats ---
    acct_col_1 = df.columns.get_loc("ACCTNBR")
    date_col_1 = df.columns.get_loc("OPEN_DATE")

    ws1.set_column(acct_col_1, acct_col_1, 20, acct_format)
    ws1.set_column(date_col_1, date_col_1, 15, date_format)

    # ============================================================
    # ✅ Format Sheet 2
    # ============================================================
    ws2 = writer.sheets["SAMPLE_NEW_RETAIL_MEMBERSHIPS"]

    # --- Auto-size + wrap/center all columns ---
    for idx, col in enumerate(sample_df.columns):
        max_len = min(
            80,
            max(sample_df[col].astype(str).map(len).max(), len(col)) + 2
        )
        ws2.set_column(idx, idx, max_len, wrap_center)

    # --- Override ACCT and DATE formats ---
    acct_col_2 = sample_df.columns.get_loc("ACCTNBR")
    date_col_2 = sample_df.columns.get_loc("OPEN_DATE")

    ws2.set_column(acct_col_2, acct_col_2, 20, acct_format)
    ws2.set_column(date_col_2, date_col_2, 15, date_format)

def generate_formated_excel_file(df,
                                 filename,
                                 sheet_name='Sheet1',
                                 wrap=True,
                                 align='center',
                                 valign='vcenter'):
    
    with pd.ExcelWriter(filename, engine="xlsxwriter") as writer:
        df.to_excel(writer, index=False, sheet_name=sheet_name)
        
        workbook  = writer.book
        worksheet = writer.sheets[sheet_name]
        wrap_center = workbook.add_format({
            'text_wrap': wrap,
            'align':align,
            'valign':valign 
        })
        
        
        for idx, col in enumerate(df.columns):
            max_len = min(80,max(df[col].astype(str).map(len).max(), len(col)) + 2)
            worksheet.set_column(idx, idx, max_len, wrap_center)

transform performs a groupby operation but returns a Series that is the same length as the original dataframe—aligning each group’s result back to each row.

df1['NEW'] = df1.groupby(['OLD1', 'OLD2'])['NUM'].transform('mean')



mask = df1["EXCLUDE"] == 0


df1["TRANSCRIPT_COUNT"] = (
    df[mask]
    .groupby("transcriptionid")["transcriptionid"]
    .transform("count")
    .reindex(df1.index, fill_value=0)
)

final_df['new_time_column'] = (
    pd.to_datetime(final_df['time_column'], errors='coerce').dt.date
    .astype("object")
    .where(final_df['time_column'].notna(), None)
)

d['COLUMN_NAME'].str.len().max()


won['DATE_COL'].dt.to_period('M').dt.to_timestamp('M')

final_df1['MONTH_END'] = pd.NaT
final_df1.loc[final_df1['CONDITION_COLUMN'] == 3, 'OG_COLUMN'] = (
    final_df1['DATE_COL']
      .dt.to_period('M')
      .dt.to_timestamp('M')
)


def read_txt_file(file_name,
                  path_name='',
                  encoding="utf-8",
                  errors="replace",
                  return_value = 'list'):
    
    '''
    
    
    '''

    filepath = f"{path_name}{file_name}"
    with open(filepath, "r", encoding=encoding, errors=errors) as f:
        lines = [line for line in f if line]
    
    if return_value=='str':
        text = ''
        text += ''.join(lines)
        return text 
            
    return lines

def compare_text_files(file,file1,
                       print_length=100,
                       validation_length=20,
                       confirmation_space=10000):
    
    '''
    
    
    
    
    '''
    
    
    print(f'Length File:  {len(file)}\nLength File1: {len(file1)}')
    
    
    # Compare. 
    # Does it matter how Long? If over 1M should I sample.
    
    
    test_length = max(len(file),len(file1))
    
    for count in range(test_length):
        if file[count]!=file1[count]:
            print(f'At Position {count} there is a noted Difference.\nFile 1 Text:{file[count:count+print_length]}\nFile 1 Text:{file1[count:count+print_length]}')
            return []
        elif count in range(confirmation_space,test_length,confirmation_space):
            print(f"\nValidating Output, At Position:{count}.\nFile: {file[count:count+validation_length]}\nFile1:{file1[count:count+validation_length]}\n")


def generate_dict_for_df(df,
                         dict_df,
                         column_name_list=[],
                         primary_key='COLUMN'):
    
    '''
    
    
    
    '''
    
    # Need to Determine Which columns will have a Dictionary Created. If none defined, it will occur for all.
    if column_name_list ==[]:
        column_name_list = df.columns.tolist()
        
    if len(dict_df)!=len(dict_df.drop_duplicates(primary_key)):
        raise ValueError('Dictionary has Duplication, Please review before proceeding with Merge')
    
    final_df = pd.DataFrame(column_name_list,columns=[primary_key])
    final_df = final_df.merge(dict_df,on=primary_key,how='left')
    
    return final_df


METRIC_TYPE = ['BALANCE' - SPOT
               ,'VALUE'  - During Period.
               'CHANGE' - Calculation of Multiple Values.
               ,'VOLUME',,'ATTRIBUTE','RATE','FLAG', 'SCORE']


def generate_read_me(df,dictionary_source=None,column='Word'):
    
    '''
    
    
    '''

    if not dictionary_source:
        from data_d_dicts import links
        dict_df = pd.read_csv(links['google_definition_csv'])
    else:
        dict_df = pd.read_csv(dictionary_source)
    
    read_me_df = pd.DataFrame(df.columns,columns=[column])

    return read_me_df.merge(dict_df,on=column,how='left')


test = generate_read_me(df2)

def create_data_dictionary(df,
                           column_name_list=[],
                           dict_=pd.DataFrame(),
                           table_name=None,
                           dict_columns = ['Process','Categorization','Word','Definition'],
                           primary_key='Word',
                           include_frequency_count=False):
    
    '''
    
    '''
    # Need to Determine Which columns will have a Dictionary Created. If none defined, it will occur for all.
    if column_name_list ==[]:
        column_name_list = df.columns.tolist()

    # Need to determine source of Dictionary. As there could be multiple sources, need to be flexible.
    if len(dict_)==0:
        dict_ = pd.read_csv(links['google_definition_csv'])
        dict_ = dict_[dict_columns]

    # Create Baseline File, which will have items iteratively added to it

    final_df = pd.DataFrame()
    
    for word in column_name_list:
        temp_df = pd.DataFrame(df[word].unique(),columns=[primary_key])
        temp_df = temp_df.merge(dict_,on=primary_key,how='left')
        temp_df['Table Name'] = table_name
        temp_df['Column Name'] = word
        
        if include_frequency_count:
            temp_df['Frequency'] = temp_df['Word'].map(df.groupby(word)[word].size())        

        final_df = pd.concat([final_df,temp_df])

    return final_df

create_data_dictionary(df,
                       column_name_list=['Process','Categorization'],
                       table_name='D Learning Notes',
                       include_frequency_count=True,
                       dict_=dict_)


df = pd.read_csv(links['d_learning_notes_url'])
df.drop(['PRO_ORDER','CAT_ORDER'],axis=1,inplace=True)
df


def CreatePivotTableFromTimeSeries(df,
                                   index,
                                   date_column,
                                   values,
                                   metric={'7D':7,'1M':30,'3M':90,'6M':180,'12M':365},
                                   aggfunc='sum',
                                   t_value_dict=None,
                                   skipna=True):
    
    '''
    Function to Summaryize a Time Series Dataframe into a Pivot. Creating a number of critical Metrics.

    '''
    
    if not t_value_dict:
        t_value_dict = {
            'observed_col':'MEAN_1M',
            'mean_col':'MEAN_ALL',
            'std_col':'STD_DEV_ALL',
            'observations':'OBS'
        }           
    
    
    # 1. Pivot
    if index==None:
        df1 = df.pivot_table(columns=date_column,values=values,aggfunc=aggfunc).fillna(0)
    else:
        df1 = df.pivot_table(index=index, columns=date_column, values=values, aggfunc=aggfunc).fillna(0)
        
    # 2. Capture original month columns IMMEDIATELY after pivot
    month_cols = df[date_column].sort_values().unique().tolist()
    
    unique_dates = len(month_cols)
    
    df2 = df1[[df1.columns[-1]]].copy()
       
    for metric, period in metric.items():     
        if period<unique_dates:
            df2[f'MEAN_{metric}'] = df1[month_cols[-period:]].mean(axis=1)
            df2[f'STD_DEV_{metric}'] = df1[month_cols[-period:]].std(axis=1)
            
        else:
            df2[f'MEAN_ALL'] = df1[month_cols].mean(axis=1)
            df2[f'STD_DEV_ALL'] = df1[month_cols].std(axis=1)
            completed = True
            
    if not completed:
        df2['MEAN_ALL'] = df1[month_cols].mean(axis=1)
        df2['STD_DEV_ALL'] = df1[month_cols].mean(axis=1)
        
    try:
        df2['OBS'] = len(month_cols)
        df2 = t_value_test(df2,**t_value_dict)    
    
    except:
        pass
    
    df2['MAX_ALL'] = df1[month_cols].max(axis=1,skipna=True)
    df2['MIN_ALL'] = df1[month_cols].min(axis=1,skipna=True)
    df2['MEAN_CHG'] = df2[t_value_dict['observed_col']].fillna(0)-df2[t_value_dict['mean_col']].fillna(0)
    df2['MEAN_CHG_PERC'] = abs(df2['MEAN_CHG'].fillna(0)/df2[t_value_dict['mean_col']].fillna(0))
    
    total = df2[df1.columns[-1]].sum()
                
    df2['PERC_TOTAL'] = df2[df1.columns[-1]]/total
    df2['FLAG_REVIEW'] = np.where((df2['reject_null']==1)&(df2['MEAN_CHG_PERC']>.15)&(df2['PERC_TOTAL']>.005),1,0)
    df2['FLAG_REVIEW'] = np.where((df2['reject_null']==1)&(df2['MEAN_CHG_PERC']>.25)&(df2['PERC_TOTAL']>.001),1,df2['FLAG_REVIEW'])
    
    return df1.reset_index(),df2.reset_index()

import numpy as np
import pandas as pd
from scipy import stats

def t_value_test(
    df,
    observed_col,
    mean_col,
    std_col,
    observations,
    confidence_level= 0.90,
    alternative= "two-sided",   # 'two-sided', 'greater', or 'less'
    label= None,
    add_ci= False):
    
    """
    Row-wise one-sample t test of an observed value against a reference mean, with CI.

    Parameters
    ----------
    df : DataFrame
        Input data.
    observed_col : str
        Column with the observed value being tested.
    mean_col : str
        Column with the historical/sample mean (x̄).
    std_col : str
        Column with the sample standard deviation (s). Should be ddof=1.
    observations : str
        Column with the sample size (n).
    confidence_level : float, default=0.90
        CI level and test level (1 - alpha).
    alternative : {'two-sided','greater','less'}, default='two-sided'
        Type of test: two-sided or one-sided.
    label : str or None
        Suffix label to append to output column names (e.g., '90').
    add_ci : bool, default=True
        If True, add CI for the mean and inside/outside indicators.

    Returns
    -------
    DataFrame
        Copy of df with added columns: t_stat, t_crit, reject_null, and optionally ci_low/ci_high.
    """
    out = df.copy()

    alpha = 1.0 - confidence_level
    n = out[observations].astype(float)
    s = out[std_col].astype(float)
    se = s / np.sqrt(n)
    dfree = n - 1

    # Observed t-statistic: (obs - mean) / SE
    t_stat = (out[observed_col].astype(float) - out[mean_col].astype(float)) / se

    # Critical t-value(s), vectorized by df
    if alternative == "two-sided":
        t_crit = stats.t.ppf(1 - alpha/2.0, dfree)
        reject = t_stat.abs() > t_crit
    elif alternative == "greater":
        t_crit = stats.t.ppf(1 - alpha, dfree)
        reject = t_stat > t_crit
    elif alternative == "less":
        t_crit = stats.t.ppf(alpha, dfree)
        reject = t_stat < t_crit
    else:
        raise ValueError("alternative must be 'two-sided', 'greater', or 'less'.")

    suf = "" if label is None else f"_{label}"

    out[f"t_stat{suf}"] = t_stat
    
    out[f"reject_null{suf}"] = reject.astype("Int64")  # keeps NA if any inputs are NA

    if add_ci:
        out[f"t_crit{suf}"] = t_crit
        # CI for the population mean: x̄ ± tcrit * SE
        ci_margin = t_crit * se
        out[f"ci_low{suf}"] = out[mean_col] - ci_margin
        out[f"ci_high{suf}"] = out[mean_col] + ci_margin

        inside = (out[observed_col] >= out[f"ci_low{suf}"]) & (out[observed_col] <= out[f"ci_high{suf}"])
        out[f"outside_ci{suf}"] = (~inside).astype("Int64")

    return out

cursor.execute('Delete from TABLENAME WHERE CONDITION')

update_sql_syntax = '''

cnxn = mssqldwconn("Analytics")
cursor = cnxn.cursor()
cursor.execute(sql)
cnxn.commit()
cursor.close()
cnxn.close()


'''

query_sql_syntax = '''

cnxn = mssqldwconn("Analytics")
df = pd.read_sql_query(sql,cnxn)
cnxn.close()

'''


columns = ['TRANSACTION','PRIMARY_ACTIVITY','TRANSACTION_ENTRY','TRANSACTION_CHANNEL']
values = ['TRANAMT','ABS_TRAN_AMT']

cols = columns + values

from UtilityFunctions import ViewDF
df[df['PRIMARY_ACTIVITY']==0][cols].groupby(columns).agg(
    ABS_TRAN_VAL = ('ABS_TRAN_AMT','sum'),
    NET_TRAN_VAL = ('TRANAMT','sum'),
    TXN_VOL = ('ABS_TRAN_AMT','count')
).reset_index()



cnxn = iscuconn()
cursor = cnxn.cursor()

cursor.execute(sql)
cnxn.commit()
cursor.close()
cnxn.close()
sql = '''

select * into
TABLE_NAME from TABLE_NAME2

ALTER TABLE TABLE_NAME
ADD COLUMN_NAME VARCHAR(50);

UPDATE TABLE_NAME
SET COLUMN_NAME = 0
WHERE COLUMN_NAME2 = 1 AND [COLUMN_NAME3] = 'Condition1';

ALTER TABLE TABLE_NAME
DROP COLUMN [COLUMN_NAME] 

ALTER TABLE TABLE_NAME
ALTER COLUMN [COLUMN_NAME] VARCHAR(64);

UPDATE TABLE_NAME
SET COLUMN_NAME = 'NAME'
WHERE COLUMN_NAME = 'NAME2';

INSERT INTO NewTable
SELECT *
FROM ExistingTable;

ALTER TABLE Analytics.CURRENT_MONTH.CURRENT_OD_POSITION
ADD 
    COLUMN_NAME VARCHAR(64),
    COLUMN VARCHAR(64)

ALTER TABLE Analytics.CURRENT_MONTH.CURRENT_OD_POSITION
    DROP COLUMN 
        COLUMN_NAME1,
        COLUMN_NAME2


EXEC sp_rename 
    'TABLE_NAME.[COLUMN_NAME]', 
    'NEW_COLUMN_NAME', 
    'COLUMN';