In [2]:
object_dict.keys()

dict_keys(['Example', 'objects_manual_cat_list', 'problem_framework_relative_order', 'problem_solving_framework', 'machine_learning_process', 'data_dictionary_columns', 'activity_notes', 'hex_color_list', 'template_doc_string', 'emoji_dict'])

In [5]:
print(object_dict['template_doc_string']['python_object'])

    Definition of Function

    Parameters:
        List of Parameters

    Returns:
        Object Type

    date_created:29-Jun-26
    date_last_modified: 29-Jun-26
    classification:TBD
    sub_classification:TBD
    usage:
        Example Function Call

In [ ]:
def manual_object_df(export_location=None):
    
    '''
    
    '''

    if not export_location:
        export_location = '/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx'

    df = pd.DataFrame(object_dict.values())
    df['key'] = object_dict.keys()
    
    final_df = pd.DataFrame()
    
    for item in df[df['publish']==1]['key']:
        temp = object_dict[item]
        temp_df = pd.DataFrame(temp['python_object'],columns=['Word'])
        temp_df['Categorization'] = temp['Categorization']
        temp_df['Process'] = temp['Process']
        final_df = pd.concat([final_df,temp_df])    
    
    final_df['Order'] = final_df.groupby(['Process']).cumcount()+1
    final_df['Categorization'] = np.where(final_df['Categorization']=='Process','Process Step',final_df['Categorization'])
    final_df[['Process','Categorization','Word','Order']].to_excel(export_location,index=False)

In [7]:
import pandas as pd
import numpy as np
import datetime

import sys
sys.path.append("/Users/derekdewald/Documents/Python/Github_Repo/d_py_functions")

from objects_manual import object_dict
object_dict.keys()

df = pd.DataFrame(object_dict.values())
df['key'] = object_dict.keys()

final_df = pd.DataFrame()

for item in df[df['publish']==1]['key']:
    temp = object_dict[item]
    temp_df = pd.DataFrame(temp['python_object'],columns=['Word'])
    temp_df['Categorization'] = temp['Categorization']
    temp_df['Process'] = temp['Process']
    final_df = pd.concat([final_df,temp_df])    

final_df['Order'] = final_df.groupby(['Process']).cumcount()+1
final_df['Categorization'] = np.where(final_df['Categorization']=='Process','Process Step',final_df['Categorization'])
#final_df[['Process','Categorization','Word','Order']].to_excel('/Users/derekdewald/Documents/Python/Github_Repo/Streamlit/Data/object_manual_published.xlsx',index=False)
final_df

                   Word  Categorization          Process  Order
0          Process Step  Reference List    Documentation      1
1        Relative Order  Reference List    Documentation      2
2           Column List  Reference List    Documentation      3
3   Material Change Log  Reference List    Documentation      4
4        Reference List  Reference List    Documentation      5
..                  ...             ...              ...    ...
5           DESCRIPTION     Column List  Data Dictionary      6
6                METRIC     Column List  Data Dictionary      7
7                 NOTES     Column List  Data Dictionary      8
8           RECORD_TYPE     Column List  Data Dictionary      9
9           UPDATE_DATE     Column List  Data Dictionary     10

[61 rows x 4 columns]

In [11]:
final_df['Categorization'].value_counts()

Categorization
Process Step      35
Column List       10
Filter Order       9
Reference List     7
Name: count, dtype: int64

In [10]:
final_df.head(40)

,Word,Categorization,Process,Order
0,Process Step,Reference List,Documentation,1
1,Relative Order,Reference List,Documentation,2
2,Column List,Reference List,Documentation,3
3,Material Change Log,Reference List,Documentation,4
4,Reference List,Reference List,Documentation,5
5,Reference String,Reference List,Documentation,6
6,Reference Dictionary,Reference List,Documentation,7
0,Process Definition,Filter Order,Notes,1
1,Definition,Filter Order,Notes,2
2,Process Step,Filter Order,Notes,3
3,Guiding Principle,Filter Order,Notes,4
4,Guidance,Filter Order,Notes,5
5,Expected Outcomes,Filter Order,Notes,6
6,Parameter,Filter Order,Notes,7
7,Algorithm,Filter Order,Notes,8
8,Information,Filter Order,Notes,9
0,Goal Setting,Process Step,Problem Solving Framework,1
1,Problem Definition,Process Step,Problem Solving Framework,2
2,Current State Assessment,Process Step,Problem Solving Framework,3
3,Data Collection,Process Step,Problem Solving Framework,4
4,Root Cause Analysis,Process Step,Problem Solving Framework,5
5,Research and Exploration,Process Step,Problem Solving Framework,6
6,Option Generation,Process Step,Problem Solving Framework,7
7,Solution Design,Process Step,Problem Solving Framework,8
8,Feasibility Assessment,Process Step,Problem Solving Framework,9
9,Prioritization and Decision Making,Process Step,Problem Solving Framework,10
10,Implementation Planning,Process Step,Problem Solving Framework,11
11,Execution,Process Step,Problem Solving Framework,12
12,Testing and Validation,Process Step,Problem Solving Framework,13
13,Evaluation,Process Step,Problem Solving Framework,14
14,Optimization,Process Step,Problem Solving Framework,15
15,Documentation and Knowledge Sharing,Process Step,Problem Solving Framework,16
16,Monitoring,Process Step,Problem Solving Framework,17
17,Continuous Improvement,Process Step,Problem Solving Framework,18
18,"Governance, Risk, and Ethics",Process Step,Problem Solving Framework,19
0,Goal Setting,Process Step,Machine Learning Lifecycle,1
1,Problem Definition,Process Step,Machine Learning Lifecycle,2
2,Data Collection,Process Step,Machine Learning Lifecycle,3
3,Data Preparation,Process Step,Machine Learning Lifecycle,4
4,Exploratory Data Analysis,Process Step,Machine Learning Lifecycle,5

In [12]:
final_df.tail(20)

,Word,Categorization,Process,Order
6,Feature Selection,Process Step,Machine Learning Lifecycle,7
7,Model Selection,Process Step,Machine Learning Lifecycle,8
8,Training,Process Step,Machine Learning Lifecycle,9
9,Hyperparameter Tuning,Process Step,Machine Learning Lifecycle,10
10,Model Evaluation,Process Step,Machine Learning Lifecycle,11
11,Validation,Process Step,Machine Learning Lifecycle,12
12,Model Interpretability,Process Step,Machine Learning Lifecycle,13
13,Deployment,Process Step,Machine Learning Lifecycle,14
14,Monitoring,Process Step,Machine Learning Lifecycle,15
15,"Bias, Fairness, and Ethics",Process Step,Machine Learning Lifecycle,16
0,FINALNAME,Column List,Data Dictionary,1
1,COLUMN,Column List,Data Dictionary,2
2,METRIC_TYPE,Column List,Data Dictionary,3
3,METRIC_CLASSIFICATION,Column List,Data Dictionary,4
4,PRODUCT,Column List,Data Dictionary,5
5,DESCRIPTION,Column List,Data Dictionary,6
6,METRIC,Column List,Data Dictionary,7
7,NOTES,Column List,Data Dictionary,8
8,RECORD_TYPE,Column List,Data Dictionary,9
9,UPDATE_DATE,Column List,Data Dictionary,10

In [9]:
final_df[final_df['Process']=='Problem Solving Framework']

,Word,Categorization,Process,Order
0,Goal Setting,Process Step,Problem Solving Framework,1
1,Problem Definition,Process Step,Problem Solving Framework,2
2,Current State Assessment,Process Step,Problem Solving Framework,3
3,Data Collection,Process Step,Problem Solving Framework,4
4,Root Cause Analysis,Process Step,Problem Solving Framework,5
5,Research and Exploration,Process Step,Problem Solving Framework,6
6,Option Generation,Process Step,Problem Solving Framework,7
7,Solution Design,Process Step,Problem Solving Framework,8
8,Feasibility Assessment,Process Step,Problem Solving Framework,9
9,Prioritization and Decision Making,Process Step,Problem Solving Framework,10
10,Implementation Planning,Process Step,Problem Solving Framework,11
11,Execution,Process Step,Problem Solving Framework,12
12,Testing and Validation,Process Step,Problem Solving Framework,13
13,Evaluation,Process Step,Problem Solving Framework,14
14,Optimization,Process Step,Problem Solving Framework,15
15,Documentation and Knowledge Sharing,Process Step,Problem Solving Framework,16
16,Monitoring,Process Step,Problem Solving Framework,17
17,Continuous Improvement,Process Step,Problem Solving Framework,18
18,"Governance, Risk, and Ethics",Process Step,Problem Solving Framework,19

In [28]:
object_dict['problem_solving_framework']

{'Process': 'Problem Solving Framework',
 'Categorization': 'Process',
 'Word': 'Problem Solving Framework',
 'Definition': 'Structured approach to solving complex problems.',
 'publish': 1,
 'python_object': ['Goal Setting',
  'Problem Definition',
  'Current State Assessment',
  'Data Collection',
  'Root Cause Analysis',
  'Research and Exploration',
  'Option Generation',
  'Solution Design',
  'Feasibility Assessment',
  'Prioritization and Decision Making',
  'Implementation Planning',
  'Execution',
  'Testing and Validation',
  'Evaluation',
  'Optimization',
  'Documentation and Knowledge Sharing',
  'Monitoring',
  'Continuous Improvement',
  'Governance, Risk, and Ethics']}

In [21]:
final_df['Categorization'].value_counts()

Categorization
Process           35
Relative Order    10
Column List       10
Reference List     7
Name: count, dtype: int64

In [29]:
import os
os.listdir('')

['consolidated_notes.csv']

In [14]:
object_dict[item]['python_object']

['FINALNAME',
 'COLUMN',
 'METRIC_TYPE',
 'METRIC_CLASSIFICATION',
 'PRODUCT',
 'DESCRIPTION',
 'METRIC',
 'NOTES',
 'RECORD_TYPE',
 'UPDATE_DATE']

In [2]:
df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vTjXiFjpGgyqWDg9RImj1HR_BeriXs4c5-NSJVwQFn2eRKksitY46oJT0GvVX366LO-m1GM8znXDcBp/pub?gid=469651051&single=true&output=csv')
df1 = pd.read_csv(df[df['Definition']=='Notes']['CSV'].item())

In [9]:
df2 = df1[df1['Process']=='Problem Framework']

df2['Word'].tolist()

['Goal Setting',
 'Problem Definition',
 'Data Collection',
 'Data Preparation',
 'Exploratory Data Analysis',
 'Feature Engineering',
 'Feature Selection',
 'Validation/ Model Selection',
 'Training',
 'Hyperparameter Tuning',
 'Model Evaluation',
 'Validation',
 'Model Summarization / Model Interpretability',
 'Deployment',
 'Monitoring']